### ISSUE TITLE
how about the method CreatePollItem in rc1

### ISSUE THREAD

**Issue by TamerDev** [zeromq/clrzmq#104]
I had this code working in the 2.2 version but seems like the classes CreatePollItem is replaced with something else in the new rc1, do you know how to convert this in the rc1 version:

<pre style="font-family: Andale Mono, Lucida Console, Monaco, fixed, monospace; color: #000000; background-color: #eee;font-size: 12px;border: 1px dashed #999999;line-height: 14px;padding: 5px; overflow: auto; width: 100%"><code>static void Main(string[] args)
        {
            using (ZmqContext context = ZmqContext.Create())   //similar to C: void *context = zmq_ctx_new ();
            {
                using (ZmqSocket frontend = context.CreateSocket(SocketType.ROUTER), backend = context.CreateSocket(SocketType.DEALER)) //similar to C: void *frontend = zmq_socket (context, ZMQ_ROUTER); void *backend  = zmq_socket (context, ZMQ_DEALER);
                {
                    frontend.Bind(&quot;tcp://*:5559&quot;);  //similar to C: zmq_bind (frontend, &quot;tcp://*:5559&quot;);
                    backend.Bind(&quot;tcp://*:5560&quot;);  //similar to C: zmq_bind (backend,  &quot;tcp://*:5560&quot;);

                    var pollItems = new PollItem[2]; /* this line and the next 4 lines are similar to: zmq_pollitem_t items [] = {
                                                        { frontend, 0, ZMQ_POLLIN, 0 },
                                                        { backend,  0, ZMQ_POLLIN, 0 }
                                                      */
                    pollItems[0] = frontend.CreatePollItem(IOMultiPlex.POLLIN);
                    pollItems[0].PollInHandler += (socket, revents) =&gt; FrontendPollInHandler(socket, backend);
                    pollItems[1] = backend.CreatePollItem(IOMultiPlex.POLLIN);
                    pollItems[1].PollInHandler += (socket, revents) =&gt; BackendPollInHandler(socket, frontend);

                    while (true)
                    {
                        context.Poll(pollItems, -1);
                    }
                }   //similar to C:zmq_close(frontend); &amp; C:zmq_close (backend);
            }   //similar to C:zmq_ctx_destroy (context);
        }

</code></pre>

**Comment by jgoz** [comment]
Try this:

``` c#
static void Main(string[] args)
{
    using (ZmqContext context = ZmqContext.Create())
    {
        using (ZmqSocket frontend = context.CreateSocket(SocketType.ROUTER),
                         backend = context.CreateSocket(SocketType.DEALER))
        using (var poller = new Poller(new[] { frontend, backend }))
        {
            frontend.Bind("tcp://*:5559");
            backend.Bind("tcp://*:5560");

            frontend.ReceiveReady += (sender, args) => FrontendPollInHandler(args.Socket, backend);
            backend.ReceiveReady += (sender, args) => BackendPollInHandler(args.Socket, frontend);

            while (true)
            {
                poller.Poll();
            }
        }
    }
}
```

It looks like you're creating a Queue device, in which case the `ZeroMQ.Devices.QueueDevice` may simplify things for you.

**Comment by jgoz** [comment]
I'm closing this issue as it isn't a defect.

**Comment by TamerDev** [comment]
thanks jgoz, I agree, the QueueDevice replaces my "long" code with just couple of lines, it was hard to find an example!! 

QueueDevice myQueueDevice = new QueueDevice(context, "tcp://_:5559", "tcp://_:5560", DeviceMode.Blocking);
myQueueDevice.Start();
