### ISSUE TITLE
local_thr / remote_thr not working as expected

### ISSUE THREAD

**Issue by MichaelEwe** [zeromq/clrzmq#105]
I testes the throuput benchmark programs in the way described on the zeromq website
- local_thr tcp://*:5000 256 1000
- give the local_thr some time time start up (count to 10... ;-)
- remote_thr tcp://*:5000 256 1000

Using 1000 packages of size 256 Byte works fine. Both programs terminate and the "local" programs reports the performance figures

Situation changes, if you change the package count to 2000. Now only the "remote" program terminates; the "local" program hangs forever. Maybe still waiting for packets.

As a trial I changed the "remote" program to close the socket and to terminate the context. Makes no difference at all.

The corresponding native programs from the zeromq distribution do _not_ show this behaviour,

**Comment by MichaelEwe** [comment]
Sorry, the "remote" command line actually is:
- remote_thr tcp://localhost:5000 256 1000

**Comment by jgoz** [comment]
Fixed this in master. The zeromq distributions use PUSH/PULL sockets but clrzmq was using PUB/SUB, which can drop messages when they get sent at lightning speeds.

Thanks for reporting this!
