### ISSUE TITLE
Consider a receive overload that could avoid requiring a buffer copy

### ISSUE THREAD

**Issue by danielcrenna** [zeromq/clrzmq#106]
A common subscriber scenario is you want to have high performance (blocking) but in order to do that you need to know the buffer size in advance, which is rarely useful in general applications. You can fake it by passing in some configurable buffer size and then chopping off the unread bits since the length is returned in the call. This is where returning a stream or enumerable buffer vs. a straight primitive might be useful, because it avoids having to copy the buffer, or at least I _think_ it could be doable if we have an array segment or a stream. 

Now I don't know if this is viable or if it works out in real life performance-wise vs. a buffer copy. This is how I'm doing the blocking call now:

``` csharp
public byte[] Receive()
{
    var source = new byte[BufferSize];
    var received = _socket.Receive(source);
    var target = new byte[received];
    Buffer.BlockCopy(source, 0, target, 0, received); // Any way to avoid this?
    return target;
}
```

**Comment by staticcat** [comment]
@danielcrenna I thought this was already possible. 

Try;

```
public byte[] Receive()
{
    byte[] message = null;
    int received = 0;
    message = _socket.Receive(message, out received);
    return message;
}
```

Edit: I am using the pre-release.

**Comment by danielcrenna** [comment]
I'm using the pre-release as well. Hmm. That certainly provides the intent and removes the copy from my end, but the documentation does not explicitly state "(high performance)" like my usage of the blocking method does. I wonder if the buffer copy is just happening behind the API call vs. right in the client if I use this method. I know it has to copy it sometime, the question is, does it only happen once.

**Comment by staticcat** [comment]
Sounds like something to just track down via the code. Eventually the receive used in the example I gave gives;

```
    public byte[] Receive(byte[] buffer, int flags, out int size)
    {
        size = -1;

        if (_msg.Init() == -1)
        {
            return buffer;
        }

        int bytesReceived = Retry.IfInterrupted(LibZmq.zmq_msg_recv.Invoke, _msg.Ptr, SocketHandle, flags);

        if (bytesReceived >= 0)
        {
            if (bytesReceived == 0 && LibZmq.MajorVersion < 3)
            {
                // 0MQ 2.x does not return number of bytes received
                bytesReceived = _msg.Size();
            }

            size = bytesReceived;

            if (buffer == null || size > buffer.Length)
            {
                buffer = new byte[size];
            }

            Marshal.Copy(_msg.Data(), buffer, 0, size);
        }

        if (_msg.Close() == -1)
        {
            size = -1;
        }

        return buffer;
    }
```

This would then result in two allocations of the buffer. One from the Socket.Receive call, and one from SocketProxy.Receive. This would be reduced to one as ScoketProxy:Receive(byte[] buffer, SocketFlags flags, out int size) handles the buffer being null and allocates the correct size.

Lastly there is one copy from the received message into the buffer using the marshal.

Eventually the receive call in your example ends up with;

```
   public int Receive(byte[] buffer, int flags)
    {
        int bytesReceived;

        // Use zmq_buffer_recv method if appropriate -> results in fewer P/Invoke calls
        if (buffer.Length <= MaxBufferSize && LibZmq.zmq_buffer_recv != null)
        {
            bytesReceived = Retry.IfInterrupted(LibZmq.zmq_buffer_recv.Invoke, SocketHandle, _buffer, MaxBufferSize, flags);
            int size = Math.Min(buffer.Length, bytesReceived);

            if (size > 0)Receive
            {
                Marshal.Copy(_buffer, buffer, 0, size);
            }

            return size;
        }

        if (_msg.Init(buffer.Length) == -1)
        {
            return -1;
        }

        bytesReceived = Retry.IfInterrupted(LibZmq.zmq_msg_recv.Invoke, _msg.Ptr, SocketHandle, flags);

        if (bytesReceived == 0 && LibZmq.MajorVersion < 3)
        {
            // 0MQ 2.x does not return number of bytes received
            bytesReceived = _msg.Size();
        }

        if (bytesReceived > 0)
        {
            Marshal.Copy(_msg.Data(), buffer, 0, bytesReceived);
        }

        if (_msg.Close() == -1)
        {
            return -1;
        }

        return bytesReceived;
    }
```

In this depending on the size of the buffer either LibZmq.zmq_msg_recv is called or LibZmq.zmq_buffer_recv is called. The same data copying is called and the buffer is allocated twice internal to your example, and copied again. 

Lastly what about the difference in the LibZmq calls. Well zmq_buffer_recv and zmq_msg_recv both call s_recvmsg internally its just that the message creation and clean up is done at a different stage in the call stack. 

Therefore I would suggest that the example I supplied is actually going to produce a higher performance. It will only be proven by some real world tests.

**Comment by staticcat** [comment]
So just ran a quick test. 

The example your have supplied gets around 130k messages every 10 seconds. The example I have supplied gets around 145k messages every 10 seconds. 

I am testing with a REQ - REP and are sending a message back and forward. I am only counting the time taken on the REP socket, and am including the time to send a byte array for each trip. The sending is the same in each test so wouldn't affect the results. 

Hope this all helps.

**Comment by danielcrenna** [comment]
Hi Jason,

Thanks for taking the time and sorry for the laziness.

I earmarked this to run a benchmark and look at the code this week, but you
skipped the line.

Much appreciated. I'm going to switch out my consumer to use your method
instead.

Totally pedantic stuff but you can reduce it to this:

``` csharp
public byte[] Receive()
{
int received;
var buffer = _socket.Receive(null, out received);
return buffer;
}
```

**Comment by staticcat** [comment]
@danielcrenna 

No worries happy to help out. 

With the reduction be careful. The supplied buffer is where the Receive function allocates its return buffer. The code looks like the following;

```
    public virtual byte[] Receive(byte[] buffer, SocketFlags flags, out int size)
    {
        EnsureNotDisposed();

        if (buffer == null)
        {
            buffer = new byte[0];
        }

        // removed things unrelated to the point 

        return buffer;
    }
```

If you pass in null you will most definitely get access violations or issues with the returned buffer. 

Personally I don't enjoy code like this because it breaks the reason for functions. They are meant to be abstractions so that another person doesn't need to know what is going on inside. Sadly in this case you do, taking away the time gains and adding another item to the list of only seven I can keep in my head at once. ;)
