### ISSUE TITLE
Sending Extra two  Byte (01 00) with Message sending

### ISSUE THREAD

**Issue by AnisAli** [zeromq/clrzmq#107]
I m using following code for sending message to server. When i send request to server, Server is not able to parse my messsage, because i am sending extra 2 byte with message data.

When i trace my tcp packets using wireshark i found ZMQ Send message in following format.

01 00 01 01 CB 01 00 00 00 00 00 00

and server expected following message

01 01 CB 01 00 00 00 00 00 00

Not the first two bytes 01 00

Can anyone help me regarding this issue..

```
        using (var context = ZmqContext.Create())
        {
            using (var socket = context.CreateSocket(ZeroMQ.SocketType.REQ))
            {
                socket.Connect("tcp://192.168.0.1:5556");

                byte[] message = null;
                CreateByteMessage(ref message); // Create Byte [] Message
                String requestDumpMessage = getByteString(message);
                txtrequestDmp.Text = requestDumpMessage;
                socket.Send(new Frame(message));

                byte[] receiveMessage = new byte[300];
                socket.Receive(receiveMessage);
                String returnMessage = getByteString(receiveMessage);
                txtresponseDmp.Text = returnMessage;
                txtReply.Text = System.Text.Encoding.UTF8.GetString(receiveMessage);

                socket.Close();

            }
        }
```

Thanks in advance, 

Anis

**Comment by staticcat** [comment]
@AnisAli happy to help however are you able to include your server code and what your doing for CreateByteMessage. I assume its simply resulting in something like the following.

```
byte[] message = { 1, 1, 204, 1, 0, 0, 0, 0, 0, 0 };
```

Is that correct?

**Comment by staticcat** [comment]
@AnisAli seems that the issue my relate to how your pulling out the bytes. My examples. 

Client

```
using (var context = ZmqContext.Create())
{
    using(var socket = context.CreateSocket(ZeroMQ.SocketType.REQ))
    {
        socket.Connect("tcp://localhost:
        byte[] message = { 1, 1, 204, 1, 0, 0, 0, 0, 0, 0};
        socket.Send(new Frame(message));

        byte[] receiveMessage = new byte[300];
        int size = socket.Receive(receiveMessage);

        socket.Close();
    }
}
```

Server

```
using (var context = ZmqContext.Create())
{
    using (ZmqSocket replyer = context.CreateSocket(SocketType.REP))
    {
        replyer.Bind("tcp://*:5555");

        while (true)
        {
            byte[] receiveMessage = new byte[100];
            int messageSize = replyer.receiveMessage (receiveMessage);

            // Simulate work, by sleeping
            Thread.Sleep(1000);
            // Send reply back to client
            replyer.Send(receiveMessage, messageSize, SocketFlags.None);
        }
    }
}
```

I always get back 10 bytes from the server to the client. receiveMessage has to be the size or larger than the size your expect, and receiveMessage(Byte[]) returns an int of the size it read into the buffer. 

Hope that helps. 

Edit: I am using the pre-released version of ZeroMQ. See no sense using anything else for new projects.

**Comment by svanschalkwyk** [comment]
You may be including the control frame, a counter.
