### ISSUE TITLE
Very Low Throughput

### ISSUE THREAD

**Issue by ehrlich-b** [zeromq/clrzmq#108]
According to this article: http://www.zeromq.org/results:10gbe-tests-v031 0mq should be able to handle ~2.5 million messages per second. When I try to send empty messages in a tight loop all I can manage to get is about 5000 messages per second. 

Is such low throughput expected? Are there any benchmarks I can look at for clrzmq specifically?

**Comment by tjrobinson** [comment]
From the readme:

> When reporting issues, please include the following information if possible:
> 
> Version of clrzmq and/or how it was obtained (compiled from source, NuGet package)
> Version of libzmq being used
> Runtime environment (.NET/Mono and associated version)
> Operating system and platform (Win7/64-bit, Linux/32-bit)
> Code snippet demonstrating the failure

**Comment by ehrlich-b** [comment]
Version 2.25 of the x86 NuGet package (the latest as of writing this), and whatever version of libzmq is associated with that for both client and server. Runtime .NET 4.0 on Windows 7 x64.

This is the pastebin for the client/server http://pastebin.com/kHL3G5Sx ... The client does Recv/Send and the server does Send/Recv with no data. I just ran the test again this morning and it took ~20 seconds to send 100,000 round trip messages, so ~5000 msg/second. 

I'd still like to know if there are any benchmarks for clrzmq.

**Comment by tjrobinson** [comment]
There's a set of performance benchmarks in the repository, in the ZeroMQ.SimpleTests project.

These are the results I get using the latest code from the master branch. I'm using .NET 4.0, Windows 7 x64, 16GB RAM, i7, SSD.

> Running test Hello World...
> 
> ZeroMQ version: 3.2.2
> Hello
> World
> 
> Running test Latency Benchmark...
> 
> Message size: 8 [B]
> Roundtrips: 10000
> Your average latency is 65.02 [us]
> Message size: 64 [B]
> Roundtrips: 10000
> Your average latency is 66.07 [us]
> Message size: 512 [B]
> Roundtrips: 10000
> Your average latency is 65.43 [us]
> Message size: 4096 [B]
> Roundtrips: 10000
> Your average latency is 74.38 [us]
> Message size: 8192 [B]
> Roundtrips: 10000
> Your average latency is 111.60 [us]
> 
> Running test Throughput Benchmark...
> 
> Message size: 16384 [B]
> Roundtrips: 10000
> Your average latency is 127.49 [us]
> Message size: 8 [B]
> Average throughput: 1498803 [msg/s]
> Average throughput: 95 [Mb/s]
> Message size: 64 [B]
> Average throughput: 1198783 [msg/s]
> Average throughput: 613 [Mb/s]
> Message size: 256 [B]
> Average throughput: 544359 [msg/s]
> Average throughput: 1114 [Mb/s]
> Message size: 32768 [B]
> Roundtrips: 10000
> Your average latency is 310.16 [us]
> Message size: 1024 [B]
> Average throughput: 160279 [msg/s]
> Average throughput: 1313 [Mb/s]
> Message size: 4096 [B]
> Average throughput: 41548 [msg/s]
> Average throughput: 1361 [Mb/s]
> 
> Finished running tests.

**Comment by ehrlich-b** [comment]
Interesting, it appears that the performance of PUSH/PULL verses REP/REQ is vastly different. If I revise the code to use PUSH/PULL the throughput jumps from 5000/s to over 500,000/s. 

Thanks for the help!
