### ISSUE TITLE
Filename of extracted libzmq.dll

### ISSUE THREAD

**Issue by tjrobinson** [zeromq/clrzmq#110]
The filename of the libzmq.dll that's extracted is libzmq-x64-3.0.0.0.dll

I'm sure there's a reason, but I was expecting it to be something like libzmq-x64-3.2.2-rc2.dll (based on the libzmq-version.txt in the NuGet package)

**Comment by tjrobinson** [comment]
Closing this as this project seems to be abandoned and the issue is probably no longer relevant.

**Comment by bluca** [comment]
@tjrobinson the currently maintained version is https://github.com/zeromq/clrzmq4
