### ISSUE TITLE
Recv should respect a 0 timeout

### ISSUE THREAD

**Issue by johnsietsma** [zeromq/clrzmq#12]
Another real small nitpick in an otherwise great library (thanks btw ;).

Recv(int timeout) doesn't respect a timeout of 0. I'd expect it to execute a non-blocking zmq_recv exactly once.

Is there another way to do this that I didn't spot.

The context is that I'm using zmq in a game and querying per frame (30-60 times a second). So even a small timeout has a big impact.

**Comment by Guthur** [comment]
You probably want to use Recv with the noblocking option set

Recv(SendRecvOpt.NOBLOCK);

Sorry the timeout method is just something I added for convience, the underlying 0MQ library does not have such a method and nonblock recv should probably be achieved as above. Sorry if my addition caused confusion. 

I should probably make a check for zero timeout and then use NOBLOCK.

Cheers for the positive feedback.

Michael

**Comment by Guthur** [comment]
On second thought I think I cannot really guarantee the desire behaviour with the timeout method, the advisable course is to use the NOBLOCK option as mentioned above

**Comment by johnsietsma** [comment]
Recv(int timeout) actually does call Recv(SendRecvOpt.NOBLOCK). It calls it repeatably until the timeout elapses.

Besides not respecting 0, there is also a timing bug where small timeout values will _sometimes_ fail to call zmq_recv due to an indeterminate time elapsing between timer.Start() and the test for the while loop.

I believe the solution to solve both issues with just to change the while loop to a do/while loop.

**Comment by Guthur** [comment]
yeah I just notice the small timeout issue, my solution was to start the timer, after the first iteration, but a do while is probably neater.  Sorry I forgot to actually push that fix though.

Also I think I misread the initial issue, I thought you were saying executed more than once with a timeout of 0. My bad.

I'll push with your suggestion promptly.

Cheers again

**Comment by Guthur** [comment]
ok pushed, sorry about the mix up, it's late and I've just arrived back from a business trip to London.

**Comment by johnsietsma** [comment]
No problem, it was an easy fix to make locally, just noting it for everyone benefit. It was actually a quick turn around!

It's the poll issue that's really eating up my time...
