### ISSUE TITLE
FileNotFound thrown even though lib file is extracted successfully in rc1

### ISSUE THREAD

**Issue by danielcrenna** [zeromq/clrzmq#125]
The file "libzmq.x64-3.0.0.0.dll" is successfully extracted, but after extracting the UnmanagedLibrary throws an exception saying the file could not be found:

System.TypeInitializationException: The type initializer for 'ZeroMQ.Interop.LibZmq' threw an exception. ---> System.IO.FileNotFoundException: Unable to find libzmq.dll on system path or extract it from assembly manifest resources. Inspect Trace output for more details. ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I've tried clearing out the dll from TEMP, and SYSTEM32, to ensure I'm looking at the right file. Tracing didn't help, and my own manual hack to inspect the resource names shows everything seems to look correct.

This is a breaking change from beta3. Upgrading to RC1 causes all production deployments to fail on this line.

**Comment by danielcrenna** [comment]
This was caused by my production servers having VS2012 C++ Redistributable installed when the VS2010 is required and the installs can't co-habitate (bad... bad... bad). Reverting back to VS2010 fixed the issue.

**Comment by mas-dude** [comment]
Thanks for that. I had tried deploying our service on a Windows Server 2008 R2 box and it failed with the same error as above. Installing Visual C++ 2010 Redistributable Package fixed the issue. For anyone else here is the link (http://www.microsoft.com/en-us/download/confirmation.aspx?id=5555)

**Comment by boominteractive** [comment]
I was able to fix the issue by changing compilation for x86 or x64 instead of AnyCPU
