### ISSUE TITLE
Trouble with polling

### ISSUE THREAD

**Issue by johnsietsma** [zeromq/clrzmq#13]
Hi there,

So I have some C# polling code that works as a Python port or as a straight recv, but I can't get it working with polling. Any ideas?

Here is the C# code (the commented code works):

```
   string address = "tcp://localhost:5555";

    //  Initialise 0MQ infrastructure
    using (Context ctx = new Context(1)) 
    using (Socket skt = ctx.Socket(SocketType.SUB)) {
        skt.Connect(address);
        skt.Subscribe(string.Empty, Encoding.Unicode);

        PollItem pollItem = skt.CreatePollItem(IOMultiPlex.POLLIN);
        pollItem.PollInHandler += (socket, revents) => {
            print( "Recv");
            byte[] bytesRecv = skt.Recv();
            string msg = System.Text.ASCIIEncoding.ASCII.GetString(bytesRecv);
            print( "Recv:" + msg);
        };

        PollItem[] pollItems = new PollItem[] { pollItem };

        //  Bounce the messages.
       for( int i=0; i<10; i++ ) {
            ctx.Poll(pollItems);
            /*byte[] bytesRecv = skt.Recv();
            if( bytesRecv!=null ) {
                string msg = System.Text.ASCIIEncoding.ASCII.GetString(bytesRecv);
                print( "Recv:" + msg);
            }(*/
            yield return null;
        }
```

Here is the Python port that works:

```
from zmq import *

address = "tcp://localhost:5555"

#//  Initialise 0MQ infrastructure
ctx = Context()
skt = ctx.socket(SUB)
skt.connect(address);

skt.setsockopt(SUBSCRIBE, "")

poller = Poller()
poller.register(skt, POLLIN)

for i in range(10):
socks = dict(poller.poll())
if skt in socks and socks[skt]==POLLIN:
    print skt.recv()
```

Here is the server code:
    import time
    from zmq import *

```
address = "tcp://*:5555"
messageSize = 10
roundtripCount = 3

#//  Initialise 0MQ infrastructure
ctx = Context()
skt = ctx.socket(PUB)
skt.bind(address);

#//  Start sending messages.
while True:
skt.send("hello")
print "Sent"
time.sleep(2)

print "done"
```

**Comment by johnsietsma** [comment]
Seems to be related to pointer size. I'm on a MacBook running 10.6. I'ma actually inside Unity which means MonoDevelop 2.4.2.

I defined x86 (even though it's a x64 platform) and managed to get a couple of messages out before it stopped receiving messages.

**Comment by johnsietsma** [comment]
Seems to be related to pointer size. I'm on a MacBook running 10.6. I'ma actually inside Unity which means MonoDevelop 2.4.2.

I defined x86 (even though it's a x64 platform) and managed to get a couple of messages out before it stopped receiving messages.

**Comment by Guthur** [comment]
It appears to work fine on Win32. 

Which version of the 0MQ library are you using?

Try the latest, 2.1, and see if you get the seem behaviour.

**Comment by johnsietsma** [comment]
I'm on the lastest version. Are you in x64 windows? 

I'll investigate further today and see what I can find.

**Comment by johnsietsma** [comment]
I should mention that I made a new Xcode project to build zmq so I could make it into a bundle. That may have screwed up x64 flags?

Another thing for me look into today.

**Comment by johnsietsma** [comment]
As I've already said compiling with x86 defined gets me a few recvs before it stops. I'm a bit confused why that would work.

Now I've found that if I sleep after each recv I can get messages indefinitely. Hmmm.

**Comment by Guthur** [comment]
Hi John,

I tried x64 windows tonight, and things worked ok. 

Sorry, I didn't get a chance to try Linux tonight, I had something else on which I forgot about. I'll try tomorrow.

Cheers,
Michael

**Comment by johnsietsma** [comment]
OK, thanks for trying it out. I'm not sure what else to test here.

**Comment by Guthur** [comment]
John, you are aware that 64bit mono VM on OSX is only available when you build from source?

see: http://www.mono-project.com/Mono:OSX#32_and_64_bit_support

**Comment by johnsietsma** [comment]
I'm using the Unity supplied MonoDevelop, which I think you're right, is the a x86 version.  So that would explain why I need x86 defined!

**Comment by johnsietsma** [comment]
Hmmm so if I'm building zmq from source I must need to compile it for x86 as well. How do I do that?

**Comment by johnsietsma** [comment]
Never mind, I just checked my Xcode settings and I am building the zmq lib as x86.

**Comment by Guthur** [comment]
Cool, I'm glad it's cleared up at least.

I'm closing this issue but if there is anything else just raise a ticket and we'll get it sorted.

Thanks for all your feedback, it's but great to have users that can catch all the wee issues.

Cheers,
Michael

**Comment by johnsietsma** [comment]
No it's not cleared up. I still can't poll without using a time out. I was just confirming that I'm building the zmq lib and bundle as x86.

**Comment by Guthur** [comment]
Do you mean using the method that accepts the timeout?

I thought x86 was recving messages?

I will double check POSIX tonight.

**Comment by johnsietsma** [comment]
No, if I add a sleep (not using zeromq) after each poll I can keep receiving messages.

**Comment by johnsietsma** [comment]
Summary:
    \* I'm still using the code I posted at the start. 
    \* If I compile with x86 defined I receive a few messages and then no more.
    \* If I sleep, in this case using Unity's WaitForSeconds(1) inside a coroutine, then I keep receiving message indefinitely.

I will try making a C# project outside of Unity today and see if Unity is causing any issues.

It doesn't make sense to me that this is a timing issue...

**Comment by Guthur** [comment]
Yeah, it has me a little baffled as well, just building some POSIX x86 tests now

**Comment by Guthur** [comment]
By the way, you can catch me on freenode #zeromq most times.

**Comment by Guthur** [comment]
Try putting a slight delay (1 second) before starting to poll, does it work then?

Also try placing the poll call in a try catch block, does that also make it work.

I'm noticing an unhandled exception on POSIX without either of these. It's very strange because it's neither a known issue with 0MQ or the win32 version of the binding.

**Comment by johnsietsma** [comment]
This is massively embarrassing, but it turned out to be a stupid mistake on my part. I didn't realise that Context() call zmq_init under the covers and I was using a Context for each socket. This cause zmq_init to be called more then once.

I can't explain why it caused these bizarre side effects.

Perhaps throwing an error or using singleton would help other newbs like me?

**Comment by Guthur** [comment]
Interesting.

I'm really pleased it's resolved though.

As for singleton it's not really appropriate as ZMQ allows you to have more than one context per application, you should never have to call any of the zmq_ functions directly.

Generally I have tried to make ZMQ objects act like normal C# object ie. disposal.

Here is an example of how I'd generally use the API:
https://github.com/imatix/zguide/blob/master/examples/C%23/hwclient.cs

P.S. The issue on Linux was due to the Socket binding not being complete, which throws 
a single exception.

**Comment by johnsietsma** [comment]
So the constructor of Context() calls zmq_init(). Are you saying it's legal to call that more then once?

I have a PUSH and a PUB socket. But the impls are in separate classes, so I need to share a context between them. So I dispose of things correctly but I dont always use a using block.

Thanks again for the time you've put in and the responses you've given me. Much appreciated.

**Comment by Guthur** [comment]
Yes it is perfectly fine to have more than one context, if you replace an existing context it should get disposed at some point by the GC.

You only need to share a context if you wish to use inproc transport.

There is a feature in clrzmq2 where you can use a global context.

Socket push = new Socket(SocketType.Push);
Socket pull = new Socket(SocketType.Pull);

will both share the same context, this context uses reference counting to determine when to dispose.

To poll you could use the static poller method of the context class Context.Poller( poll items );

Also note events can now be assigned to sockets and socket lists passed to the poller.

Check out the AsyncWorker project for some examples of these features. Sorry there existence is rather undocumented.

Cheers,
Michael
