### ISSUE TITLE
Support for "Any CPU" platforms

### ISSUE THREAD

**Issue by skrebbel** [zeromq/clrzmq#15]
Hi all,

I want to use ZMQ in a library that, ideally, can be used both in 64bit and 32bit applications. VS has a nice "Any CPU" build setting for this, but ZeroMQ will of course only link to the libzmq.dll with the same word size as the running application. 

I guess this could be supported transparently by determining the platform at runtime and to, (for instance) create a different child class of an interface that dictates the c function signatures. One child class could link to e.g. libzmq32.dll and the other to libzmq64.dll. This does require manually building and renaming libzmq for both platforms, but that might not be so bad, the return being not having to worry about client platforms. With some conditional compilation, the current functionality can be kept in place as well, not breaking backwards compatibility.

I would happily contribute this feature, but in all honesty I might be missing some pressing issue as to why this hasn't been done yet anyway (in any of the three clr zmq bindings). Is there any interest in a feature like this? Any reason not to do it? Also, I have zero Mono experience so no idea if this issue plays there too, and if so, if there's other potential problems with it there.

**Comment by Guthur** [comment]
I had this in the back of my mind recently as well, I didn't go too deep in the line of thought though. It would certainly be well received if you could figure out a neat way of doing this.

A number of caveats though:

It would have to maintain at least the current situation on Mono, see the linux.config file for how the dllimport is mapped to libzmq.so; probably could just map libzmq[32/64].dll both to libzmq,so.

Would be nice to have less precompiler directives if possible, these things are really horrid, I probably could have used less.

Also, though I don't think you were advocating this, I'd be very much against packaging libzmq directly with clrzmq2. 

Cheers,
Michael

**Comment by skrebbel** [comment]
Thanks for the feedback. I'm planning to dive into it this weekend. I'll try to touch the Mono part as little as possible for a first version. I'll see if I can avoid compiler directives. 

How to you test and develop on both linux and windows? I have a win 7 box so i guess i'd just install ubuntu into a virtual machine, but i'm not sure if that's the best approach.

Finally, I wasn't really advocating packaging both libraries together, though having a binary download package available (of not necessarily the cutting edge version) might be useful; f.ex. we're using vs 2008, so i had to download and install vc and vcs 2010 just to be able to use zmq in our application :-) but it's an independent discussion, indeed.

**Comment by skrebbel** [comment]
One more thing. For my own needs, a single cross-CPU approach would suffice. This means i'd in fact be _removing_ platforms from the configuration manager in favour of an "Any CPU" platform. Then, however, clrzmq2 would require the end user to choose a libzmq32.dll or libzmq64.dll filename. 

The other option is to add "Any CPU" as a platform, and keep the x86/x64 platforms link to libzmq.dll without any runtime platform checking. This solution would probably require additional precompiler directives (bad), but it keeps backward compatibility with installations that currently use clrzmq2. What's your thought here?

A final "magic" approach is to try which dll to use. Using e.g. the trick on http://stackoverflow.com/questions/970017/how-do-i-handle-a-failed-dllimport we can see if libzmq(64/32).dll can be found, and if not, try libzmq.dll. Might work, but "magic" always gives me the "unforeseen side effects" underbelly feeling.

**Comment by drusellers** [comment]
Can't we just sniff the current OS bit mode, and then load up the appropriate dll? I must be missing something.

**Comment by drusellers** [comment]
Well, this may or may not help, but you can see the 32/64 bit mode here 'System.IntPtr.Size' but you most likely already new that. If you have a dll produced for both 32bit and 64bit - we could load that up at runtime based on the IntPtr so that the correct one is used. not sure if its work the 'hack' but I would be happy to help make it happen. :)

**Comment by Guthur** [comment]
The suggestion is valid.

At the moment the library uses dllimport attribute, this is a compile time attribute. It is feasible that we could use LoadLibrary at runtime, and select the appropriate dll.

Cheers,
Michael

**Comment by drusellers** [comment]
@Guthur, if you decide to tackle it and want some help, please feel free to ping me.

-d

**Comment by simoneb** [comment]
I second this one, it would be useful to be able to have a Any CPU build so as to be able to deploy to x86 and 64 bit platforms with one single package.

**Comment by jgoz** [comment]
I have a [working branch with AnyCPU support](https://github.com/jgoz/clrzmq2/tree/anycpu) for both Windows and Linux/Mono. It uses `LoadLibrary`/`GetProcAddress` on Windows and `dlopen`/`dlsym` on Linux to bind the native calls to Delegates. This incurs a very slight performance hit on application start, but I haven't noticed any performance degradation while running.

When deployed on x64 machines, clrzmq expects an x64 build of libzmq, ditto for x86 if on that platform. If you want to run it in 32-bit mode on a 64-bit platform, you have to specifically target x86. From what I can tell, this is the default behaviour of AnyCPU binaries.

So to make up for this, I added a hacky bit that scans for `libzmq64.dll`, `libzmq32.dll` and `libzmq.dll`, in that order, when trying to load the library. The logic behind this was to allow bundled deployments of both the 64- and 32-bit native libraries on any machine, letting the clrzmq assembly choose the right one. It seems to work.

I'm not going to make an official pull request yet because I don't have a good non-trivial ZMQ implementation to test it on. All of the bundled test programs and my own small apps work without issue, but I'd appreciate it if someone could check it out and put it through the paces on a larger system.

**Comment by Guthur** [comment]
Jgoz,

That sounds great. 

Can the AnyCPU solution be made to live side by side with the old build setups, if so I think it would be worthwhile adding it to binding ASAP.

Michael

**Comment by jgoz** [comment]
Yes, you can still specifically target x64 or x86 for both Windows and Posix. AnyCPU is a third option for both platforms.

If, for example, you only had access to a 32-bit libzmq native library on a 64-bit machine, you would definitely want to use the x86 config and not the AnyCPU config.

**Comment by Guthur** [comment]
For my part I am all on for merging this in.

Any slight startup performance cost is a very minor trade off imho.

**Comment by jgoz** [comment]
Excellent. I'll need to merge in some of your recent changes, but there shouldn't be any problems.

My hesitation isn't related to the startup performance, but more related to the overall correctness/stability while running. The test cases in clrzmq solution execute without errors and I've used it without issues in my own (small) projects, but I'm sure there are much larger implementations out there that use a greater % of the API. Ideally, one of those implementers would drop in an AnyCPU binary and record their results, good or bad, before officially merging it in.

Or maybe I'm being overly cautious. That tends to happen. :)

In a few hours, I'll pull in your latest changes, make sure everything still runs, and then issue a pull request.

**Comment by chrisa23** [comment]
I am pretty confused with the AnyCPU stuff...  Is this gone now or am I missing something?  All nuget packages look cpu specific, and I can't seem to get it to build and embed both libraries myself.

**Comment by jgoz** [comment]
The AnyCPU builds are not yet considered stable. You'll have to set the "include prerelease" option in NuGet to see the 3.0 beta releases.

**Comment by invertedtomato** [comment]
I'm very interested in this AnyCPU support. I notice it has been 2 years and this still is in "prerelease" on NuGet. What's the story here?

**Comment by mcsilver** [comment]
I would also very much like AnyCPU support.  Any chance this will become a reality?
