### ISSUE TITLE
Issues with dll mapping

### ISSUE THREAD

**Issue by nilsh** [zeromq/clrzmq#16]
I'm using mono 2.10 with monodevelop, latest clrzmq2.

I have already managed to transmit some Messages, but suddenly bind() fails with a "File or Directory not found" Exception. As there is no File-related code in your bind() implementation, i assume, it is some shared library mapping issue. I haven't changed anything in my code when the error happens, i have no clue what causes the error and why it does sometimes work again...

**Comment by nilsh** [comment]
same problem with the example projects of clrzmq2 except AsyncReturn, which works in my tests.

**Comment by Guthur** [comment]
Hi nilsh,
Sorry for the delay, I was away for a couple of days, out of interest could you try reproducing the error with Mono 2.6, I use that and I have never seen this behaviour.

**Comment by nilsh** [comment]
I have experimented more with my code and now i think the problem was a race condition produced by me which caused a rep socket to not write a response but recv() again instead(or something like that). Then a ZMQ.Exception was thrown, but with this very confusing "File or Directory not found" Message. In another case the Port was simply blocked by a lost running instance of my program.
My problem is solved, but in general it would be good to get better debug info from the Error Messages.

**Comment by Guthur** [comment]
Usually if your REQ/REP sockets get out of sync in their request/response sequence it should say the socket is in an 'invalid state', which it has done for me in the past. "File or Directory not found" Message is certainly strange, I'll keep an eye out for it.

I'm glad it's working now.

Cheers,
Michael

Edit: 
When you say race condition, are you sharing the socket across threads perchance?

**Comment by nilsh** [comment]
No sharing across threads, its hard to explain what exactly happenend :-)
