### ISSUE TITLE
CLRZMQ devlopment stalled?

### ISSUE THREAD

**Issue by SemtexCharlie** [zeromq/clrzmq#161]
Just want to ask the question whether this is being actively maintained?

**Comment by tjrobinson** [comment]
I think efforts have been diverted to https://github.com/zeromq/netmq which could (should?) replace clrzmq.

**Comment by SemtexCharlie** [comment]
Thanks  - it looks like there are a few options now, e.g. Castle.  A pure C# implementation is appealing though for lots of reasons...

**Comment by tjrobinson** [comment]
Good tip about CastleZMQ, not seen that before: https://github.com/castleproject/castlezmq
