### ISSUE TITLE
Connect() and Bind(): why different overloads?

### ISSUE THREAD

**Issue by nilsh** [zeromq/clrzmq#17]
Bind() has handy overloads for 3 parameters ZMQ.Transport, string address and int port, but Connect() only for one "addr" combined connectionstring. Is this intended??

**Comment by Guthur** [comment]
Oh, oops, sorry an oversight on my part.

I added the overloads on a sort of whim and actually never really use them. I'll add the overload for connect later today.

Cheers,
Michael

**Comment by Guthur** [comment]
Sorry, didn't mean to close yet.

**Comment by Guthur** [comment]
Overloads added, Sorry for the delay.
