### ISSUE TITLE
NuGet package for 64bit

### ISSUE THREAD

**Issue by drusellers** [zeromq/clrzmq#19]
I noticed on http://nuget.org/List/Packages/clrzmq2 the package is for x86 only. Would it be possible to get a 64bit one too?

Thanks,
-d

**Comment by Guthur** [comment]
Someone else setup the NuGet stuff, I've never looked at it to be honest.

We should be able to get something sorted out. 

Cheers,
Michael

**Comment by rgl** [comment]
I've just created a x64 version of the package at http://nuget.org/List/Packages/clrzmq2-x64 be sure to use recent nuget version to install it.
