### ISSUE TITLE
Not working in wndows xp service pack 3

### ISSUE THREAD

**Issue by vinodannu** [zeromq/clrzmq#2]
Sir,
       I have downloaded from link 2 libzmq2 and downloaded visual c# 2010 also and build it ,and added the reference also. But it's giving error like this 

Could not load file or assembly 'clrzmq, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Can u please tell me the solution please.....

**Comment by Guthur** [comment]
Hi vinodannu,

It sounds a like a 32bit vs 64bit issue.

Make sure you build with correct configuration for your platform x86 (32bit) or x64 (64bit), and then import the appropriate assembly; it should be in something like <project folder>\bin\debug\x86.

When I get home tonight I will give you the exact path. I'm using it on Win7 but it should be the same.
