### ISSUE TITLE
HWD not working

### ISSUE THREAD

**Issue by helge** [zeromq/clrzmq#21]
Hi, I am on a x64 machine with libzmq.dll and clrzmq.dll as x86 libraries. My app runs as x86. zeromq works fine, but the HWD is not working. I am using a simple pub sub scenario and the process bombs out at 2 GB memory usage. 

If I set the HWD to 1 and write it to the console I get a very weired random value. Seems much like the converting is off.

In the socket class I changed
         private void WriteSizeT(IntPtr ptr, object val) {
            Marshal.WriteInt32(ptr, unchecked(Convert.ToInt32(val)));
        }
to
         private void WriteSizeT(IntPtr ptr, object val) {
            Marshal.WriteInt64(ptr, unchecked(Convert.ToInt64(val)));
        }
and I at least the HWD getter seems to work - it shows what I set it to (set to 1 -> get 1).

But still, durable but offline subscribers let the publisher bomb after a while. it seems like I had never set HWD.

Do you have any idea?
Helge

**Comment by sustrik** [comment]
Are you setting HWM on both sizes of the connection?

**Comment by helge** [comment]
yes, I do. HWM is set on the publisher socket and on the subscriber socket.
protocol is tcp

**Comment by helge** [comment]
ahhh... HWD works. My bad. I set HWD after I did the bind... stupid...
So it's just that 'Mashal.WriteInt64' thing that needed to change.
Though I have no experience with interop programming I can send you a pull request if you like.
Helge
