### ISSUE TITLE
Socket.HWM property does not pass correct value to libzmq

### ISSUE THREAD

**Issue by afrost408** [zeromq/clrzmq#22]
Setting the Socket.HWM property does not work correctly i.e. the wrong value is passed to the native ZMQ library.

The value of HWM passed into setsockopt() must be a 64 bit value - regardless of whether the host OS is x86 or x64. The clrzmq .NET wrapper is only setting the lower 32 bits, instead of all 64 bits. This is due to a call to WriteSizeT() which in turn calls Marshal.WriteInt32()

public void SetSockOpt(SocketOpt option, ulong value) {
    int sizeOfValue = Marshal.SizeOf(typeof(ulong));
    using (DisposableIntPtr valPtr = new DisposableIntPtr(sizeOfValue)) {
        WriteSizeT(valPtr.Ptr, value);  // THIS IS WRONG - only the lower 32 bits get set, higher 32 bits contain garbage
        if (C.zmq_setsockopt(_ptr, (int)option, valPtr.Ptr, sizeOfValue) != 0)
        {
            throw new Exception();
        }
    }
}

The size of the pointer is 32 bits, but the value it points to is 64 bits i.e. __int64 on Windows. When I set the HWM to 10, the lower 32 bits contains 10, but the higher 32 bits contains garbage. So I end up with a huge value for HWM - whihc in practice behaves as if HWM has not been set at all

This problem was discussed initially on the ZMQ mailing list:

http://lists.zeromq.org/pipermail/zeromq-dev/2011-May/011522.html

**Comment by jgoz** [comment]
Looks like this should use `Marshal.WriteInt64()` directly. The [ZMQ API](http://api.zeromq.org/2-1:zmq-setsockopt) lists HWM as a `uint64_t`, not a `size_t`.

**Comment by Guthur** [comment]
Yes indeed it should have been Marshal.WriteInt64()

The other options suffered similar issues, all should be resolved now.

Not sure what was going through my head there, _face palm_

Cheers
Michael
