### ISSUE TITLE
Application, that use clrzmq2 freezes in context.cs on exit

### ISSUE THREAD

**Issue by umaxfun** [zeromq/clrzmq#26]
Hello,

On exit, my application freezes at this line of Context.cs:

<pre>
protected virtual void Dispose(bool disposing) {
            if (_ptr != IntPtr.Zero) {
                int rc = C.zmq_term(_ptr); // &lt;------------------------------------------------------------
                _ptr = IntPtr.Zero;
                if (rc != 0)
                    throw new Exception();
            }
        }
</pre>

Is it a bug or I do something wrong?

Cheers,

**Comment by sustrik** [comment]
You have to close all the sockets before closing the context. The other possible reason is there's data queued to be sent, but the peer is offline. You can adjust the waiting time using LINGER option.

**Comment by jgoz** [comment]
@umaxfun Are you still experiencing this issue?

**Comment by umaxfun** [comment]
We had to drop zeromq from our project due to its unpredictability. It acted the way it wished, not the logical, both server and client side =(

**Comment by jgoz** [comment]
I'm sorry to hear that it wasn't working predictably for you.

Over the next couple of months, the focus for clrzmq2 will be improving reliability, adding test cases and writing C#-specific documentation. And maybe with more eyes on the project, the kinds of issues you were experiencing will be resolved.

Thank you for the feedback.
