### ISSUE TITLE
Not getting any data on client side

### ISSUE THREAD

**Issue by vinodannu** [zeromq/clrzmq#3]
Hi guy's here is my server code and client code .I am not getting any data from server to client
I have executed Client server on visual c# 2010. Please tell me corrections
SERVER:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZMQ;
namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            using (Context context = new Context(1))
            {
                using (Socket publisher = context.Socket(SocketType.PUB))
                {
                    publisher.Connect("tcp://localhost:5556");

```
                //  Initialize random number generator
                Random rand = new Random(System.DateTime.Now.Millisecond);
                while (true)
                {
                    //  Get values that will fool the boss
                    int zipcode, temperature, relHumidity;
                    zipcode = rand.Next(0, 100000);
                    temperature = rand.Next(-80, 135);
                    relHumidity = rand.Next(10, 60);

                    //  Send message to all subscribers
                    string update = zipcode.ToString() + " " + temperature.ToString() +
                        " " + relHumidity.ToString();
                    publisher.Send(update, Encoding.Unicode);
                }
            }

        }
    }
}
```

}
 Client code:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZMQ;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Collecting updates from weather server...");
            // Prepare our context
            using (var context = new Context(1))
            {
                // Socket to talk to server
                using (var subscriber = context.Socket(SocketType.SUB))
                {
                    subscriber.Connect("tcp://localhost:5556");

```
                // Subscribe to zipcode, default is NYC, 10001
                string filter = "10001 ";
                subscriber.Subscribe(filter, Encoding.Unicode);
                int totalTemp = 0;
                int updateNbr = 0;
                for (; updateNbr < 10; updateNbr++)
                {
                    string update = subscriber.Recv(Encoding.Unicode);
                    Console.WriteLine(update);

                    totalTemp += Convert.ToInt32(update.Split()[1]);
                }
                Console.WriteLine("Average temperature for zipcode {0} was {1}F",
                    filter, totalTemp / updateNbr);
            }
        }
    }
}
```

}

**Comment by vinodannu** [comment]
check it

**Comment by Guthur** [comment]
Sorry about that vinodannu, small bug in the server code.

It should bind to the port not connect.

use:
publisher.Bind("tcp://*:5556");

Again sorry about that, and thanks for raising the issue.

Michael
