### ISSUE TITLE
Exception & Errno Consistency with underlying lib

### ISSUE THREAD

**Issue by dowlingw** [zeromq/clrzmq#32]
Some improvements to make the error handling more consistent:
- ZMQ.ERRNOS should be updated to include all ZMQ error codes
- ZMQ.ERRNOS.EAGAIN (and any other platform-dependant values exposed from the ZEROMQ lib) should contain the correct value for the target platform (WIN/POSIX)
- ZMQ.Exception.Errno should be parsed into a ZMQ.ERRNOS value

These changes would help projects utilising this library handle exceptions cleanly without having to assume things about the 0MQ library at the lower layer.

**Comment by jgoz** [comment]
I agree with all of your suggestions, but there's one issue:

> - ZMQ.Exception.Errno should be parsed into a ZMQ.ERRNOS value

This would be an API change and will have to be reserved for a major release, likely one corresponding with ZMQ 3.0. The first two suggestions can be included without problems.
