### ISSUE TITLE
Bundling ZMQ dll's with clrzmq

### ISSUE THREAD

**Issue by fholm** [zeromq/clrzmq#36]
I feel like it would be a good idea to bundle the correct ZMQ x86-32 and x86-64 binaries that are guaranteed to be compatible with clrzmq in the repo itself.

This would both lower "startup" cost for new people (that dont pull from nuget) and it would make it easy to make sure any changes that get done get tested against a defined set of binaries.

**Comment by jgoz** [comment]
I agree with you, but I would like to avoid committing the binaries directly into the repo. This is to minimize unnecessary bloat when versions are bumped and to allow for multiple target versions of libzmq when 3.1 support is started.

The approach I had in mind would be to create a separate NuGet package for just the native DLLs (the 32- and 64-bit binaries could be included in the same package). There's already a dependency installation script in the clrzmq repository, so we'd just need to hook into that. Supporting multiple simultaneous versions could be done by including both versions in the same package or by creating a separate package for 3.x. I'm not sure what the best option is yet.

What are your thoughts on that?

I'll likely work on this in the next couple of days. I was planning to add development environment setup information to the Readme, anyway.

**Comment by fholm** [comment]
This seems like a good compromise to me, though I do not fully agree with the "bloat" argument. You could just have two folders, one for 2.x and one for 3.x. The DLLs will not update that often and it's very convenient to have the code tied to a specific DLL version so you're always sure you have a compatible DLL even if you look far back in the version history, etc.

**Comment by jgoz** [comment]
The history argument is a strong one, but this can be taken care of by inspecting the packages.config file that will reference the native NuGet package. The native packages will be versioned according to the actual libzmq versions they contain (which means 2.x and 3.x will need separate packages after all). So even if, for some reason, the old packages are removed from the NuGet gallery, someone could inspect the packages.config file and get the libzmq version number for that particular point in history.

If this approach proves to be too brittle, I'll break down and check it into the repo.

**Comment by fholm** [comment]
Ok, seems like a good compromise :)

**Comment by jgoz** [comment]
Thanks Fredrik. Place your bets now on where the theory breaks down :)

**Comment by sustrik** [comment]
Btw, there's a win7 box in our build environment. If there's a way to run the build automatically, we can make win version of clrzmq part of the daily builds (note that linux version of clrzmq is already built within daily builds). The results of the builds are public and available for download.

**Comment by jgoz** [comment]
Good to know. I'm in the process of adding a build script (and READMEs, etc.) so setting up automated builds shouldn't be a problem. Do you already have a CI tool set up on the win7 box?

**Comment by sustrik** [comment]
You should speak to Mikko Koppanen who's taking care of the build environment. He's hanging around on the IRC and on the mailing list. Let me introduce you. I think it shouldn't be a problem to install any infrastructure you need there.
