### ISSUE TITLE
Devices should either capture ETERM or pass it on via the thrown Exception

### ISSUE THREAD

**Issue by daveduchene** [zeromq/clrzmq#41]
zmq_device always returns -1, and hence ZMQ.Socket.Device.Create() will always throw an empty Exception when the underlying context is closed.

**Comment by jgoz** [comment]
The `Socket.Device` class will disappear in the next major release, as `zmq_device` has been taken out of 0MQ 3.1. Proper ETERM handling will be baked in throughout clrzmq 3.

I'm close to a v3 beta release, so this will get fixed in the 2.2 branch soon.

**Comment by jgoz** [comment]
Until I package a new release, you can clone the [2.2](https://github.com/zeromq/clrzmq/tree/2.2) branch to get this fix.

**Comment by daveduchene** [comment]
Thanks very much.
