### ISSUE TITLE
EAGAIN handling in Send

### ISSUE THREAD

**Issue by jgoz** [zeromq/clrzmq#43]
(Originated in an email from Tim Corbett.)

`Socket.Send` currently throws an Exception upon seeing an `EAGAIN` result, which is incorrect behaviour. This should, instead, propagate the result back to the user, who may try the operation again.

**Comment by sustrik** [comment]
C++ binding does a similar thing. It returns a message if one is available, false if there's none (EAGAIN) and throw exception in case of any other error.
