### ISSUE TITLE
SocketExt.Recv<T>(this Socket skt, int timeout) raises a SerializationException because of an empty stream

### ISSUE THREAD

**Issue by gbaurand** [zeromq/clrzmq#49]
when using SocketExt.Recv<T>(this Socket skt, int timeout), every call fails with a SerializationException
This is due to the instanciation of the MemoryStream : 
var ms = new MemoryStream { Position = 0 };

It should be :
var ms = new MemoryStream(data) { Position = 0 };

This modification solves the problem

**Comment by jgoz** [comment]
Can you please submit this as a pull request off of the [2.2](https://github.com/zeromq/clrzmq/tree/2.2) branch? That will help me out a bit.
