### ISSUE TITLE
Using Clrzmq2

### ISSUE THREAD

**Issue by vinodannu** [zeromq/clrzmq#5]
Sir,

 string update=subsciber.recive(encoding.ASCII);

I am sending data in binary foramte from ubuntu server(64 bit ) and receiving data on windows c# application.

On windows side i a have used clrzmq2 In that program i try to recive data in binary formate but no option available to recive in binary formate.Like Encoding.binary
           string update=subsciber.recive(encoding.ASCII);

ANy body please help me how can i receive binary data from 64 bit machine to 32 bit windows c# application of clrzmq2;

**Comment by vinodannu** [comment]
Please respond

**Comment by Guthur** [comment]
The method which you pass an encoding object to is specifically for strings. 

You want to use the standard send and recv which work on byte arrays (binary).
