### ISSUE TITLE
Documentation on GitHub appears to be out of date

### ISSUE THREAD

**Issue by IanMercer** [zeromq/clrzmq#50]
The example code doesn't match the Nuget delivered assemblies.

**Comment by jgoz** [comment]
The documentation for the master branch matches the clrzmq-3.0.0-alpha1 release, which can be installed via NuGet using the `-Pre` switch (or by targeting that version explicitly). The documentation for the stable release on NuGet is on the [2.2](https://github.com/zeromq/clrzmq/tree/2.2) branch.
