### ISSUE TITLE
Nuget bundled version of libzmq.dll gives assert error on Windows XP when using epgm

### ISSUE THREAD

**Issue by gerdus** [zeromq/clrzmq#51]
version 2.2.2

Bundled version of libzmq.dll gives assert error on Windows XP when using epgm and pgm transport.

Building libzmq using openpgm from http://miru.hk/openpgm/ does not give the assert on windows xp.

Probably this bug https://zeromq.jira.com/browse/LIBZMQ-202 thus happens because of openpgm before 5.1.118.

**Comment by jgoz** [comment]
I'll verify the version of libzmq (and openpgm) included with 2.2.2. I don't have a Windows XP machine to test on, unfortunately, so I may ask for your assistance.

**Comment by jgoz** [comment]
I've released a new version v2.2.3 to NuGet and GitHub. This fixes a few minor issues and bundles libzmq 2.1.11, which includes OpenPGM 5.1.118. It was using 5.1.115 before, which is probably the root of your issue.

Can you please test it out and re-open this issue if the problem persists? I don't have an XP machine available.

**Comment by gerdus** [comment]
Yes, it is fixed now. I have tested on my XP virtual machine and it is working.
Thank you.
