### ISSUE TITLE
ZmqSocket.Recieve(buffer, timeout) does not throw exception with REQ on time-out and blocks indefinitely on Dispose

### ISSUE THREAD

**Issue by MarshallChris** [zeromq/clrzmq#52]
version 3.1.1

There appears to be a dfferent behaviout with this function for a REP socket to  a REQ socket.

The rep sockets will timeout as expected, throwing an exception.

REQ Socket Problem:

If the server does not exist, the code will return from a send as sent. The req socket will return from a timeout with a -1, but will then block on dispose and will never progress.

If I explicitly set send and receive timeouts on the socket, this makes no difference.

``` c#
int byteCount = 0;

using (ZmqContext ctx = ZmqContext.Create())
{
    using (ZmqSocket skt = ctx.CreateSocket(SocketType.REQ))
    {
        string id = "muxIdcStatusOut";
        byte[] ident = Encoding.ASCII.GetBytes(id);
        skt.Identity = ident;

        TimeSpan time = new TimeSpan(0, 0, 0, 0, RECEIVE_TIMEOUT_MS);

        // set timeout explicitly
        skt.ReceiveTimeout = time;
        skt.SendTimeout = time;

        skt.Connect(m_ipAddress + ":" + m_port);

        SocketFlags sf = SocketFlags.None;

        // different send makes no difference
        //skt.Send(msg, msg.Length, sf, time );
        SendStatus ss = skt.Send(msg, time);

        Console.WriteLine(ss.ToString());

        reply = new byte[4];
        byteCount = skt.Receive(reply, time);

        // if no server - will never reply from this
        skt.Close();
    }
}

// never gets here if server down
Console.WriteLine(Encoding.ASCII.GetString(reply));


```

**Comment by jgoz** [comment]
I'll investigate this when I get a spare moment. In the meantime, have you tried setting the `ZmqSocket.Linger` option? See the [socket options](http://api.zeromq.org/3-1:zmq-setsockopt) page for details.

**Comment by MarshallChris** [comment]
I thought I may need polling, and have been trying to implement the lpclient.cs example, without luck.

After your suggestion I tried in my original code

``` c#
skt.Linger = new TimeSpan(0,0,0);
```

This works! Brilliant, thanks.

**Comment by jgoz** [comment]
Great! Glad to help.
