### ISSUE TITLE
Unable to compile with vs2010

### ISSUE THREAD

**Issue by ezrover** [zeromq/clrzmq#55]
C:\Dropbox\Proj.Server\Library\zMQ-clrzmq\zeromq-clrzmq-c913100\src\ZeroMQ\ZeroMQ.csproj : error  : Unable to read the project file 'ZeroMQ.csproj'. 
C:\Dropbox\Proj.Server\Library\zMQ-clrzmq\zeromq-clrzmq-c913100\src\ZeroMQ\ZeroMQ.csproj(95,3): The imported project "C:\Users\Administrator\Desktop\adamstantonvan-zeromq.net-4609164\src\CustomTasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by ezrover** [comment]
actually clrzmq compiles standalone but when u try to add it to another project, it is unable to import the project settings correctly!

I also tried to get it using nugget:

libzmq 3.1.1-beta1
ØMQ (ZeroMQ) is an open source, high performance transport layer. This package includes compiled versions of the native libzmq library for x86 and x64.

To install libzmq, run the following command in the Package Manager Console

PM> Install-Package libzmq -Pre

but i get this error:

Install-Package : A parameter cannot be found that matches parameter name 'Pre'.
At line:1 char:28
- Install-Package libzmq -Pre <<<< 
  - CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
  - FullyQualifiedErrorId : NamedParameterNotFound,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by jgoz** [comment]
If you're using the PM console, you can't use `-Pre`, you have to use `-IncludePrerelease`. [PowerShell documentation](http://docs.nuget.org/docs/reference/package-manager-console-powershell-reference#Install-Package)

I'm confused on what you're trying to do. Were you adding the ZeroMQ project to your own solution? If so, you'll need to copy the `CustomTasks.targets` file to a known location and modify the `ZeroMQ.csproj` file to point to it.

**Comment by ezrover** [comment]
wonderful. thanks so much
