### ISSUE TITLE
unabl compile libzmq with vs2010 either!

### ISSUE THREAD

**Issue by ezrover** [zeromq/clrzmq#56]
------ Rebuild All started: Project: libzmq, Configuration: Debug Win32 ------
          1 file(s) copied.
  precompiled.cpp
  address.cpp
  clock.cpp
  ctx.cpp
  decoder.cpp
  devpoll.cpp
  dist.cpp
  encoder.cpp
  epoll.cpp
  err.cpp
  fq.cpp
  io_object.cpp
  io_thread.cpp
  ip.cpp
  ipc_address.cpp
  ipc_connecter.cpp
  ipc_listener.cpp
  kqueue.cpp
  lb.cpp
  mailbox.cpp
  msg.cpp
  Generating Code...
  Compiling...
  mtrie.cpp
  object.cpp
  options.cpp
  own.cpp
  pair.cpp
  pgm_receiver.cpp
  pgm_sender.cpp
  pgm_socket.cpp
  pipe.cpp
  poll.cpp
  poller_base.cpp
  pub.cpp
  pull.cpp
  push.cpp
  random.cpp
  reaper.cpp
  rep.cpp
  req.cpp
  select.cpp
  session_base.cpp
  Generating Code...
  Compiling...
  signaler.cpp
  socket_base.cpp
  stream_engine.cpp
  sub.cpp
  tcp_address.cpp
  tcp_connecter.cpp
  tcp_listener.cpp
  thread.cpp
  trie.cpp
  xpub.cpp
  xrep.cpp
......\src\xrep.cpp(94): warning C4800: 'const int' : forcing value to bool 'true' or 'false' (performance warning)
  xreq.cpp
  xsub.cpp
  zmq.cpp
  zmq_utils.cpp
  Generating Code...
     Creating library C:\Dropbox\Proj.Server\Library\LibZMQ\bin\Win32../../lib/Win32/libzmq_d.lib and object C:\Dropbox\Proj.Server\Library\LibZMQ\bin\Win32../../lib/Win32/libzmq_d.exp
zmq.obj : error LNK2019: unresolved external symbol "int __cdecl zmq::device(class zmq::socket_base_t *,class zmq::socket_base_t *)" (?device@zmq@@YAHPAVsocket_base_t@1@0@Z) referenced in function _zmq_device
C:\Dropbox\Proj.Server\Library\LibZMQ\builds\msvc\libzmq../../../bin/Win32/libzmq_d.dll : fatal error LNK1120: 1 unresolved externals
------ Rebuild All started: Project: remote_thr, Configuration: Debug Win32 ------
  remote_thr.cpp
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_term referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_close referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_close referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_sendmsg referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_init_size referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_connect referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_socket referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_strerror referenced in function _main
remote_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_init referenced in function _main
C:\Dropbox\Proj.Server\Library\LibZMQ\builds\msvc\c_remote_thr../../../bin/Win32/remote_thr_d.exe : fatal error LNK1120: 9 unresolved externals
------ Rebuild All started: Project: local_thr, Configuration: Debug Win32 ------
  local_thr.cpp
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_term referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_close referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_close referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_stopwatch_stop referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_stopwatch_start referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_size referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_recvmsg referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_init referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_bind referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_socket referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_strerror referenced in function _main
local_thr.obj : error LNK2019: unresolved external symbol __imp__zmq_init referenced in function _main
C:\Dropbox\Proj.Server\Library\LibZMQ\builds\msvc\c_local_thr../../../bin/Win32/local_thr_d.exe : fatal error LNK1120: 12 unresolved externals
------ Rebuild All started: Project: remote_lat, Configuration: Debug Win32 ------
  remote_lat.cpp
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_term referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_close referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_close referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_stopwatch_stop referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_size referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_recvmsg referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_sendmsg referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_stopwatch_start referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_data referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_init_size referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_connect referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_socket referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_strerror referenced in function _main
remote_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_init referenced in function _main
C:\Dropbox\Proj.Server\Library\LibZMQ\builds\msvc\c_remote_lat../../../bin/Win32/remote_lat_d.exe : fatal error LNK1120: 14 unresolved externals
------ Rebuild All started: Project: local_lat, Configuration: Debug Win32 ------
  local_lat.cpp
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_term referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_close referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_sleep referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_close referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_sendmsg referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_size referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_recvmsg referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_msg_init referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_bind referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_socket referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_strerror referenced in function _main
local_lat.obj : error LNK2019: unresolved external symbol __imp__zmq_init referenced in function _main
C:\Dropbox\Proj.Server\Library\LibZMQ\builds\msvc\c_local_lat../../../bin/Win32/local_lat_d.exe : fatal error LNK1120: 12 unresolved externals
------ Rebuild All started: Project: inproc_lat, Configuration: Debug Win32 ------
  inproc_lat.cpp
  inproc_lat.vcxproj -> C:\Dropbox\Proj.Server\Library\LibZMQ\builds\msvc\inproc_lat../../../bin/Win32/inproc_lat_d.exe
------ Rebuild All started: Project: inproc_thr, Configuration: Debug Win32 ------
  inproc_thr.cpp
  inproc_thr.vcxproj -> C:\Dropbox\Proj.Server\Library\LibZMQ\builds\msvc\inproc_thr../../../bin/Win32/inproc_thr_d.exe
========== Rebuild All: 2 succeeded, 5 failed, 0 skipped ==========

**Comment by jgoz** [comment]
Please log this issue on the libzmq project page.
