### ISSUE TITLE
Possible memory leaks on exceptions after Marshal.AllocHGlobal

### ISSUE THREAD

**Issue by rgl** [zeromq/clrzmq#6]
Review the code that uses Marshal.AllocHGlobal, for example, if this code (zmq.cs) throws an exception, a memory leak is created:

```
    public void SetSockOpt(SocketOpt option, ulong value) {
        int sizeOfValue = Marshal.SizeOf(typeof(ulong));
        IntPtr valPtr = Marshal.AllocHGlobal(sizeOfValue);
        WriteSizeT(valPtr, value);
        if (C.zmq_setsockopt(ptr, (int)option, valPtr, sizeOfValue) != 0)
            throw new Exception();
        Marshal.FreeHGlobal(valPtr);
    }
```

Probably, the IntPtr that are returned from Marshal.AllocHGlobal should be wrapped by an IDisposable object (in a using block), or by try finally blocks.

**Comment by Guthur** [comment]
Thanks very much for catching this, and the fix suggestions.

I have pushed some code which should fix the issue.

If you notice any problems with code reopen this ticket.
