### ISSUE TITLE
On Windows/C#, the socket handler returned by the property Socket.FD doesn't seem to be correct

### ISSUE THREAD

**Issue by mauri-melato** [zeromq/clrzmq#60]
Hello, 
  I'm writing a C# application that uses ZMQ as the underlying network/communication layer and 
I've got an apparently improper value using the file descriptor property of a Socket, Socket.FD.

The application creates a ZMQ REP socket and bind it to localhost port 7777.
Accessing socket.FD I'd expect to get the handle of the socket listening to port 7777
but that's not what happens. 
The handler belongs instead to another socket created internally by ZMQ.

I've created a short self-contained sample to show what I mean at the URL: http://ideone.com/nxJnf
The example creates a REP socket on tcp://127.0.0.1:7777 and then closes it using a p/invoke call to closesocket
on its handler.
Before and after closing the socket, it launches netstat to show the sockets open by the program itself.

Here an example of a netstat before closing the socket

```
 TCP    127.0.0.1:3324         127.0.0.1:3325         ESTABLISHED     5952
 TCP    127.0.0.1:3325         127.0.0.1:3324         ESTABLISHED     5952
 TCP    127.0.0.1:3326         127.0.0.1:3327         ESTABLISHED     5952
 TCP    127.0.0.1:3327         127.0.0.1:3326         ESTABLISHED     5952
 TCP    127.0.0.1:3328         127.0.0.1:3329         ESTABLISHED     5952
 TCP    127.0.0.1:3329         127.0.0.1:3328         ESTABLISHED     5952
 TCP    127.0.0.1:3330         127.0.0.1:3331         ESTABLISHED     5952
 TCP    127.0.0.1:3331         127.0.0.1:3330         ESTABLISHED     5952
 TCP    127.0.0.1:3332         127.0.0.1:3333         ESTABLISHED     5952
 TCP    127.0.0.1:3333         127.0.0.1:3332         ESTABLISHED     5952
 TCP    127.0.0.1:7777         0.0.0.0:0              LISTENING       5952
```

and then after:

```
TCP    127.0.0.1:3324         127.0.0.1:3325         ESTABLISHED     5952
TCP    127.0.0.1:3325         127.0.0.1:3324         ESTABLISHED     5952
TCP    127.0.0.1:3326         127.0.0.1:3327         ESTABLISHED     5952
TCP    127.0.0.1:3327         127.0.0.1:3326         ESTABLISHED     5952
TCP    127.0.0.1:3328         127.0.0.1:3329         ESTABLISHED     5952
TCP    127.0.0.1:3329         127.0.0.1:3328         ESTABLISHED     5952
TCP    127.0.0.1:3330         127.0.0.1:3331         ESTABLISHED     5952
TCP    127.0.0.1:3331         127.0.0.1:3330         ESTABLISHED     5952
TCP    127.0.0.1:7777         0.0.0.0:0              LISTENING       5952     
```

As you can see the closed socket is the one used for the connection on ports 3333/3332.

Please consider this code just as a spike to show the error condition explained above. 
The real application is not going to use the socket.FD to close the socket, that's also explicitly "discouraged" by the ZMQ guide.
The actual final goal was to use the underlying socket handler in another p/invoke call to make the socket
not-inheritable by child processes...but that's another story.

We are using the last stable version (built today) of both libzmq (zeromq-2.2.0) and clrzmq (2.2.2-12).

Thank you very much for your attention.

Best regards, 
Mauri

**Comment by jgoz** [comment]
I don't think this is a bug in clrzmq. `Socket.FD` just returns the value received from `zmq_getsockopt` for the `ZMQ_FD` option. The 0MQ API docs state the following:

> The returned file descriptor is intended for use with a poll or similar system call only. Applications must never attempt to read or write data to it directly, neither should they try to close it.

The fact that your 0MQ socket is listening on 7777 doesn't mean that the underlying listener socket is the same one that will be used to read/write data from/to other sockets. The netstat output would indicate that there are 10 internal sockets associated with the one 0MQ socket you're using and `Socket.FD` happens to return the one listening on port 3333.

Given that the socket returned by `ZMQ_FD` is intended to be used for polls or other event loops, the socket listening on 7777 will never be returned, as it only exists to listen for incoming connections and pass them off to the read/write sockets.

I'm going to close this issue, as it is not an issue with clrzmq. If you would like finer-grained access to the various underlying sockets that 0MQ sockets may use, you will have to make a case for this to be added into libzmq.

**Comment by sustrik** [comment]
Yes. The FD returned is an internal object, not the actual listening socket. You can for example bind to two endpoints (port 5555 and 7777) -- in such case would be no way to decide which socket to return.

**Comment by mauri-melato** [comment]
Thank you very much for your answers. 

The problem is that you cannot avoid child processes to inherit 0MQ sockets like you could do with standard sockets.

I think this may limit usage scenarios but I'm going to submit this question directly to the 0MQ project to understand if it makes sense to them and if it may be also useful for others.

**Comment by sustrik** [comment]
Did you really meant "cannot avoid inheriting sockets"?

If so, the internal FDs are marked with O_CLOEXEC, thus when you fork and exec, the inherited fds will be closed automatically.

**Comment by mauri-melato** [comment]
This does not happen on Windows, for which afaik there is no support for O_CLOEXEC flag.

The way to do it in Windows would be to use the SetHandleInformation (http://msdn.microsoft.com/en-us/library/windows/desktop/ms724935(v=vs.85).aspx) on the sockets FDs, 

```
SetHandleInformation(socketFD, HANDLE_FLAG_INHERIT, 0);
```

My C# application binds on a port, accepts requests and forks child processes.
If the appl. dies for some reason it cannot be restarted since the port results as already bound.
Killing child processes (that's something we don't want to do) I can finally restart the appl.

I hope this will be considered something to be fixed in the libzmq for Windows platforms.

Thanks again for your support.

**Comment by sustrik** [comment]
Hm, we sre using SOCKETs, not HANDLEs. Any idea how to prevent inheritance is such a case?

**Comment by mauri-melato** [comment]
If you do something like

```
SOCKET socketfd = socket(family, type, protocol);
```

well 'socketfd' is actually the socket handle and so you can just call:

```
SetHandleInformation((HANDLE) socketfd, HANDLE_FLAG_INHERIT, 0);
```

and this prevents your socket to be inherited.

**Comment by sustrik** [comment]
Patch submitted to XS project. If there are no complaints it will be merged into mainline in couple of days.

**Comment by mauri-melato** [comment]
That's a great, thanks a lot for your support! 
Is there a way for me to track the discussion about the patch and to understand in which version it may become available ?

**Comment by sustrik** [comment]
Ah, sorry. XS is a fork of ZeroMQ: www.crossroads.io

**Comment by jgoz** [comment]
@mauri-melato You may wish to review Martin's patch and submit it as a pull request against libzmq. That may be the quickest way for you to take advantage of it and I'm sure the ZMQ folks would appreciate it.

Someone else may eventually do this, but as far as I know, this issue is only being tracked here. At the very least, you may want to log a bug in the ZeroMQ JIRA tracker.

**Comment by sustrik** [comment]
It's few lines of code. It should be easy to backport it to libzmq.

**Comment by mauri-melato** [comment]
@sustrik, the patch does not work. I'm working on and testing a new patch I'm going to submit to the zmq project tomorrow.

I'll keep you informed, thanks.

**Comment by sustrik** [comment]
What's the problem with the patch?

**Comment by mauri-melato** [comment]
It doesn't cover all the cases where the library creates or gets a new socket.
The patch below seems to work correctly: https://github.com/zeromq/zeromq2-x/pull/51
