### ISSUE TITLE
AcceptanceTests Faild

### ISSUE THREAD

**Issue by ghost** [zeromq/clrzmq#61]
Hi, 
I currently checkout Ref. 2.2 from the Repository and found that the AcceptanceTests failed.

packages\Machine.Specifications.0.5.6.0\tools\mspec-x86.exe  tests\AcceptanceTests\bin\x86\WIN_RELEASE\AcceptanceTests.dll

Specs in AcceptanceTests:

Bind/Connect, when binding and connecting to a tcp ip address and port
» should not fail

Bind/Connect, when binding to a tcp port and connecting to address and port
» should not fail

Bind/Connect, when binding and connecting to a named inproc address
» should not fail

Connect, when connecting to a pgm socket with pub and sub
Warn: Interface {846EE342-7039-11DE-9D20-806E6F6E6963} reports as a loopback device.
» should not fail
Warn: Interface {846EE342-7039-11DE-9D20-806E6F6E6963} reports as a loopback device.

**Comment by jgoz** [comment]
Those don't look like failures to me. Perhaps the specification names should be changed to "should not throw an exception", but those tests are passing.

The warnings are from PGM because the tests connect to 127.0.0.1, which is a loopback device and is not suitable for multicast.

**Comment by jgoz** [comment]
I'm going to close this issue for now. If you confirm that there are actual test failures, please feel free to re-open it.

Thank you!
