### ISSUE TITLE
Interoperability between Win32 - Win64

### ISSUE THREAD

**Issue by estumarnis** [zeromq/clrzmq#64]
Hi, 

just want to ask whether someone in here ever faced this kind of issue:

If we connecting Win64SUB to WIn32PUB, the SUB won't receive any single message.  
This issue is only happened in WIn64PUB - Win32SUB scheme only, if the connection scheme is changed to Win64REP-Win32REQ, it's working.

The problem that I face also won't happened if the connection scheme is the other way around (Win32SUB connecting to Win64PUB).  

Any hint is highly appreciated.

**Comment by jgoz** [comment]
Have you tried asking this question on the zeromq mailing list? It sounds like an internal zeromq issue (i.e., not clrzmq) and you'll reach a much wider audience there. It would be helpful to specify which version you are using too. The stable branch of clrzmq targets libzmq 2.1.

**Comment by estumarnis** [comment]
sorry for not mentioning the version in my earlier post, I'm using the latest stable libzmq version 2.2 with latest stable version of clrzmq.

**Comment by jgoz** [comment]
No problem. I still think you should send an email to zeromq-dev@lists.zeromq.org, as this sounds like an issue in libzmq itself.

**Comment by jgoz** [comment]
Just doing some housecleaning - I tried duplicating this with the latest 2.2 release and subscriptions between 32-64 and 64-32 bit PUB/SUB worked as expected. If this is still an issue for you, please re-open this defect.

**Comment by estumarnis** [comment]
Dear john,
Im already upgrading the module to version 3, working without any issue.

Thanks for your kind assistance and contribution.

Regards,
