### ISSUE TITLE
NuGet package build output won't run on machines without VS2010

### ISSUE THREAD

**Issue by Thirsty2** [zeromq/clrzmq#65]
I built a simple project using VS2010, and took advantage of the almost great NuGet package.  I had to choose the 32 bit package for some reason, even though I am building on a 64 bit Win 7 machine.  That is another issue, but the main problem I had is that when I copied the binaries to a clean (no VS2010 installed) machine, they won't run because the NuGet package contains libzmq.dll binaries that were dynamically linked to the VS2010 runtime.  I tested on a 64 bit Win 7 Home Premium machine.  When I rebuilt my own version of libzmq.dll using the latest code, removed the nuget package and added my manually built libzmq.dll, It worked fine.  The libzmq.dll distributed in the latest NuGet package should be rebuilt, and tested to run on a machine without VS2010 installed.

**Comment by jgoz** [comment]
You don't actually need full VS2010 to be installed on the target machine. It is sufficient to use the VC++ Redistributable Pack ([x64](http://www.microsoft.com/en-us/download/details.aspx?id=14632) | [x86](http://www.microsoft.com/en-us/download/details.aspx?id=5555)).

When you say you rebuilt with the latest code, which version are you talking about (i.e., the latest 'libzmq' repo, zeromq3-x, zeromq2-x, etc.)? The stable NuGet packages currently target the 2-x branch, which uses the /MD flag by default, telling libzmq to link to the VC++ runtime dynamically (as opposed to statically). See a discussion of dynamic vs static runtime linking [here](http://stackoverflow.com/questions/787216/should-i-link-to-the-visual-studio-c-runtime-statically-or-dynamically).

I would prefer to keep libzmq.dll dynamically linked to the runtime, as this precedent has already been set and I don't see a compelling reason to switch. It is trivial to install the redist pack on servers and it can easily be included in an installer that will run on a user's machine.

If a later version of libzmq.dll uses static linking by default, then this will propagate to later clrzmq NuGet packages when they get released.

**Comment by Thirsty2** [comment]
Thank you for the help.  I installed the x86 redistributable as you suggested, and it did the trick.
