### ISSUE TITLE
Support for zmq_ctx_set_monitor

### ISSUE THREAD

**Issue by rohitjoshi** [zeromq/clrzmq#66]
I see ZeroMQ has a support for zmq_ctx_set_monitor which allows to get notified on event such as new connection accepted/bind etc..
This is particularly useful for "slow joiner" where we are loosing the first message.

http://api.zeromq.org/3-3:zmq-ctx-set-monitor

By the way, thx a lot for clrzmq, we used for out  new product prototype and now going to use in production.

**Comment by jgoz** [comment]
Hi, sorry for the delay on responding. I will ensure this gets added once ZMQ 3.3 is released.

**Comment by jgoz** [comment]
Actually, this looks like it exists in 3.2.0-rc1. I'll work on it when I get a spare moment.

**Comment by ievgent** [comment]
I have an zmq_ctx_set_monitor implementation.
The idea is: we have separate class ZmqMonitor which can expose following event:
        public event EventHandler<ZmqMonitorFileDescriptorEventArgs> Connected;
        public event EventHandler<ZmqMonitorErrorEventArgs> ConnectDelayed;
        public event EventHandler<ZmqMonitorIntervalEventArgs> ConnectRetried;
        public event EventHandler<ZmqMonitorFileDescriptorEventArgs> Listening;
        public event EventHandler<ZmqMonitorErrorEventArgs> BindFailed;
        public event EventHandler<ZmqMonitorFileDescriptorEventArgs> Accepted;
        public event EventHandler<ZmqMonitorErrorEventArgs> AcceptFailed;
        public event EventHandler<ZmqMonitorFileDescriptorEventArgs> Closed;
        public event EventHandler<ZmqMonitorErrorEventArgs> CloseFailed;
        public event EventHandler<ZmqMonitorFileDescriptorEventArgs> Disconnected;

EventArgs looks like:
     public class ZmqMonitorEventArgs<T> : EventArgs
    {
        public ZmqMonitorEventArgs(ZmqSocket socket, string address, T value)
        {
            this.Socket = socket;
            this.Address = address;
            this.Value = value;
        }

```
    public ZmqSocket Socket { get; private set; }
    public string Address { get; private set; }
    public T Value { get; private set; }
}
```

CreateMonitor() will be added to the ZmqContext class to register and instantiate monitor.
ZmqMonitor.Dispose will be used to unregister monitor.

I can push this if you agree with this idea?

**Comment by jgoz** [comment]
@XMbIPEK, seems like a good approach. Please open a pull request and I'll happily review & merge.

**Comment by rohitjoshi** [comment]
Thanks you guys!!
