### ISSUE TITLE
clrzmq uses too much CPU when wait time on receive() is longer

### ISSUE THREAD

**Issue by rohitjoshi** [zeromq/clrzmq#72]
We use clrzmq in our Windows 7 embedded system to communicate with external server.  For subscription socket, when receive  () function uses longer  timeout, it uses almost 100% of the CPU.

 For now, as a work around, we just pass 1 mill sec timeout and CPU usage drops to 1-3%.  Looking at the code, it seem to use spinwait instead of thread-sleep to avoid context switching but for low end system, that uses more cpu particularly when messages are expected at every 1-60 sec interval.

We tried to use no timeout but that blocks until message is received which is good but there is no way to interrupt for graceful shutdown.

**Comment by jgoz** [comment]
Yes, that's definitely `SpinWait` at work. I think it's time to re-think the timeout-handling code in ZmqSocket.

I'll try an alternate implementation in a separate branch. Once I have something that I think will work better, will you be able to help me test it? I don't have any low end test systems that run .NET.

**Comment by rohitjoshi** [comment]
Thanks for a quick response. Sure, I will be happy to test on our embedded/.NET system.

**Comment by ievgent** [comment]
Have you looked at the Poller class?

**Comment by jgoz** [comment]
@rohitjoshi Please check out the [72-cpu-usage](https://github.com/zeromq/clrzmq/tree/72-cpu-usage) branch and let me know if that works better for you.

On my quad-core i5 system, 1 PUB and 5 SUB sockets went from 100% CPU usage down to about 1 or 2%, so I would call this a significant improvement. Hopefully your results agree with mine.

Thank you again for targeting the master branch and logging this issue.

EDIT: I should clarify that I tested this with 2 ranges of random timeouts: 100ms - 5000ms and 1ms - 50ms. Both ranges produced similar low CPU usage results.

**Comment by rohitjoshi** [comment]
I did try on my laptop and it is much better. Still need to try out on embedded device.  
Quick note: It doesn't work with ZeroMQ version 3.1. It throws exception in LibZmq.NET.cs at line 40 which is
zmq_msg_get = NativeLib.GetUnmanagedFunction<ZmqMsgGetProc>("zmq_msg_get");

I checked out ZeroMQ 3.2-rc1 and seem to work fine.

**Comment by jgoz** [comment]
> I did try on my laptop and it is much better. Still need to try out on embedded device.

Great. I'll merge the fix into master, but I'll wait to hear from you before closing the defect.

> Quick note: It doesn't work with ZeroMQ version 3.1.

Correct, the master branch is now targeting version 3.2. 3.1 will not become a stable release.

**Comment by rohitjoshi** [comment]
I tried this branch on my embedded device. With older clrzmq, eceive() function with wait time  250 millsec uses 40% CPU (without any data coming in) versus 0% CPU with your patch.  Thanks a lot.

Please let me know once it is merge with mainline trunk. Also waiting for ctx_monitor patch. Once both of these patches are available, I will do through testing of Publish/Subscribe and Request/Response part of the code.

**Comment by jgoz** [comment]
Perfect, glad it worked. I'll merge it in a few hours.

> Also waiting for ctx_monitor patch.

I'm in the process of adding tests for @XMbIPEK's monitoring patch. Apparently some of the monitoring events do not work (bugs in libzmq), but I'm not sure which ones yet. Once it's reasonably tested, I'll merge it into master.

**Comment by rohitjoshi** [comment]
Thanks!!

**Comment by ievgent** [comment]
Hi John!
Here is the link to my pull request with fix. https://github.com/zeromq/zeromq3-x/pull/23
After applying this fix, all monitor events works as expected.
Let me know if something goes wrong.

**Comment by jgoz** [comment]
Thanks Eugene. If this doesn't get merged in before I'm ready to release another 3.0 beta, I'll do it manually for the clrzmq packages.
