### ISSUE TITLE
Bad Pointer Exception when using a Pair Socket

### ISSUE THREAD

**Issue by ghost** [zeromq/clrzmq#77]
Hello,
There is an issue with the current implementation where the same object is being used by both the send and receive portions of the socket and will cause a crash in LIBZMQ. This will cause an issue where the message is being deleted in the send or receive functions when its being used by the other function. Even if this was thread safe, the same message object should not be used by both sends and receives. Also because this message is stored in the internal ZMQ pipe, I'm not certain that multiple calls to either the send or recv function should even use the same message.

The crash occurs in the encoder.hpp file in the get_data function on the line "memcpy (buffer + pos, write_pos, to_copy);" Essentially, since the message has been deleted write_pos ends up being set to 0xfeeefeee. That special code is used by the HeapFree() function in Windows to mark when an object has been deallocated. When you trace where the write_pos variable is set, it works its way all the way up to being the IntPtr _msg variable in socket.cs.

The problem can be resolved by removing single reference to IntPtr _msg in the socket class and replacing it with a unique IntPtr _msg in the send and recv functions. I believe the same change needs to be made in the forward function as well.

Happy bug hunting,
= Aaron

**Comment by jgoz** [comment]
Good investigation work. clrzmq has been using a single _msg variable since long before I was the maintainer, so PAIR must not be a popular socket type :smiley:.

The prior solution was attempting to reduce the number of heap allocations required for sending/receiving, but this is obviously a dangerous optimization. A fix similar to your pull request #78 is definitely required.

**Comment by ghost** [comment]
Thank you for the compliment.. I'm not sure how long you've run this project, but that probably means that the pair patter isn't being used often at all. :) Reducing the number of heap allocations defiantly makes sense, but in this case I don't think it can be avoided.
