### ISSUE TITLE
GetSockOpt on x86 fails

### ISSUE THREAD

**Issue by matthiasg** [zeromq/clrzmq#8]
The DisposableIntPtr for "val" built in GetSockOpt in the non IDENTITY case needs to be 64bit in size even in x86 builds. IntPtr.Size is not correct here.

In Release this would corrupt memory. In Debug builds on the Dipose call it leads to Handle Invalid.

PS: Sorry for adding the issue twice, I accidentally closed the previous issue.

**Comment by matthiasg** [comment]
Size needs to be 8

**Comment by Guthur** [comment]
Hi Matthiasg,

No problem on the double post.

Many thanks for catching this issue and raising it, it is much appreciated.

I have pushed a fix.

Michael

**Comment by matthiasg** [comment]
thanks for the quick response!
