### ISSUE TITLE
Timeouts not handled

### ISSUE THREAD

**Issue by pushedx** [zeromq/clrzmq#80]
Version: 
zeromq-clrzmq-v3.0.0-beta1-45-gd438272

Platform: 
Windows 7 x64 (using x86 build) / .Net / compiled from build.cmd

Issue: 
Timeouts are not properly handled anywhere in the "SendReceiveExtensions.cs" code.

Comments:
Any function that accept a timeout value is not consistently coded to actually handle the event when a timeout happens. The specific function that I triggered was:

```
public static string Receive(this ZmqSocket socket, Encoding encoding, TimeSpan timeout)
        {
            VerifySocket(socket);
            VerifyEncoding(encoding);

            int messageSize;
            byte[] buffer = socket.Receive(null, timeout, out messageSize);

            return encoding.GetString(buffer, 0, messageSize);
        }
```

After a timeout, buffer is an empty 0 length byte array, non-null, that triggers an illegal index exception inside "encoding.GetString" (messageSize = -1). Upon further checking all functions inside the "SendReceive.cs" function, none of them seem to implement timeout handling.

Replication: The easiest way is to setup a REP socket, bind, then call Receive with a timeout. Catching an exception for a timeout is not an issue, but the fact it's an inconsistent exception is a problem. I cannot provide fixes myself (to the project) because a design decision has to be made to use exceptions to report timeouts or another error reporting mechanic (null, set a status, etc...).

Thank you!

**Comment by jgoz** [comment]
Thank you for catching this.

Exceptions to report timeouts is definitely the wrong way to go. This issue only affects extension methods that return a string, so they will need to be fixed to handle empty buffers. `socket.ReceiveStatus` will already be set to `TryAgain` if a timeout expires, so this behaviour does not need to change.
