### ISSUE TITLE
W7 freezing solid (also Assertion failure fds.size () <= FD_SETSIZE)

### ISSUE THREAD

**Issue by dave-uk** [zeromq/clrzmq#82]
I have tried building the example code from The Guide and it locked my W7 machine requiring a hard reboot.
To eliminate some things and to get more information I changed the example to 1) set the HWM on all sockets to 10 and 2) to change the client.Send line to add a incrementing number to each Hello message. However, the problem occurs with the unmodified code too.

It seems to follow a pattern. The first time I run the demo code it runs for a little over 1000 iterations then aborts with Assertion failed: fds.size () <= FD_SETSIZE (......\src\select.cpp:69).

The second time I run it very much the same thing happens except I get a couple of messages displayed after the Assertion failure (which is reasonable due to threading).

The third time I run it, after 70-odd iterations, it slows dramatically then stops. The windows rapidly but progressively dies, eventually requiring it to be powered off to regain control.

I don't know if the exact number of iterations is the same each time as I never noted the numbers and I don't fancy trying it too often. Windows is hardly forgiving of power-off reboots. If it's likely to help I'm game to do so though. I will write them down the next time I try it, if anyone else has any suggestions that may fix the problem

People have suggested it may be opening too many sockets in a short time period (the code only opens 15 sockets, each once) . ESET was also suggested as a possible culprit but disabling that made no difference. I may try totally removing it to see if that helps.

Version of clrzmq and/or how it was obtained (compiled from source, NuGet package)
2.2.5

Version of libzmq being used
the one included in the above nuget package

Runtime environment (.NET/Mono and associated version)
.NET VS2012 RC

Operating system and platform (Win7/64-bit, Linux/32-bit)
W7 Pro. 64-bit  (I've tried both 64-bit & 32-bit builds)
ESET NOD32 AV software (v 4.0.467.0) but I disabled this and the problem still occurs.

Code snippet demonstrating the failure
 http://zguide.zeromq.org/cs:lruqueue2 using the version of ZMessage at https://github.com/imatix/zguide/blob/master/examples/C%23/zmsg.cs since this isn't in the clrzmq package.

**Comment by jgoz** [comment]
Well, this is a puzzler.

Before I set up a VS2012 VM to test this out, I'd like to isolate the problem a little better.

Could you please use the libzmq.dll file included with the NuGet package and run the C version of the LRU queue (http://zguide.zeromq.org/c:lruqueue2). Ideally (for me) this will also fail and indicate that the problem is not in clrzmq. If it passes, though, there may be some (severe) compatibility issues that need to be sorted out with .NET 4.5.

**Comment by dave-uk** [comment]
I've tried to do this but I'm having no luck in getting the C++ version to
link. I get a lot of errors like

error LNK2019: unresolved external symbol __imp__zmq_errno referenced in
function "public: __thiscall zmq::error_t::error_t(void)" (??0error_t@zmq
@@QAE@XZ)

Please could you give me some guidance as to what I need to do to get the
C++ stuff to link. I've never used C++ under VS and  seem to be missing a
step. I have:
- Added the zmq lib  and bin directories to Project Properties | Linker
  | General | Additional Library Directories
- Added libzmq-v100-mt-gd.lib  libzmq-v100-mt.lib to Project Properties
  | Linker | Input | Additional Dependencies
- Added the ZMQ include directory to Project Properties | C/C++ |
  General | Additional Include Directories.
- I've also copied the DLLs from the ZMQ bin directory to a fonder on
  the PATH.

What else do I need to do???

Regards

Dave

**Comment by jgoz** [comment]
Hopefully this isn't past the point of relevance for you, but I figured out the reason you were hitting that assertion: the code in the Guide had a bug in ClientTask. It should look like this:

``` c#
private static void ClientTask()
{
    using (var ctx = new Context(1))
    {
        using (var client = ctx.Socket(SocketType.REQ))
        {
            ZHelpers.SetID(client, Encoding.Unicode);
            client.Connect("tcp://localhost:5555");

            while (true)
            {
                //  Send request, get repl
                client.Send("HELLO", Encoding.Unicode);
                string reply = client.Recv(Encoding.Unicode);

                if (string.IsNullOrEmpty(reply))
                {
                    break;
                }

                Console.WriteLine("Client: {0}", reply);
            }
        }
    }
}
```

Note that the lines

``` c#
ZHelpers.SetID(client, Encoding.Unicode);
client.Connect("tcp://localhost:5555");
```

are _outside_ of the `while` loop, while in the Guide they are _inside_. This would cause the client to repeatedly open connections to the frontend until the `FD_SETSIZE` limit was reached (1024).

On my machine (W7 x64, VS2012 release) I did not observe any lockups, though, so this may be localized to your environment.

**Comment by jgoz** [comment]
This will be fixed with [pull request 256](https://github.com/imatix/zguide/pull/256).
