### ISSUE TITLE
zguide.zeromq.org - Samples are outdated. 

### ISSUE THREAD

**Issue by staticcat** [zeromq/clrzmq#84]
Basically it seems that a great number of the samples are out of date since a major interface change. 

E.g. 

http://zguide.zeromq.org/cs:asyncsrv

ZMessage doesn't exist any more, and the code doesn't even compile. 

I would offer to help write these examples up, however as I am still learning this might prove very unfruitful.

**Comment by tjrobinson** [comment]
I would be willing to help with this, though I am also still learning and fairly busy at the moment.

However, first it might be better to create an issue against the zguide repository instead of here:
https://github.com/imatix/zguide

**Comment by staticcat** [comment]
Also logged here. 

https://github.com/imatix/zguide/issues/241

**Comment by jgoz** [comment]
@staticcat and @tjrobinson 

Some additional help would be most appreciated. This is on my ever-growing TODO list and is necessary to promote the new API 'stable' status. IMO, re-writing the examples would be a great way to learn ZMQ and the C# API, especially with myself and others reviewing the output.

**Comment by tjrobinson** [comment]
I've made a start updating the C# samples, I hope to have a pull request soon (a few days).

**Comment by jgoz** [comment]
@tjrobinson Excellent! Thanks very much for taking this on.

**Comment by staticcat** [comment]
For the guide I have come across the following code... 

```
ZHelpers.Dump(sink, Encoding.Unicode);
```

What would be the replacement for this in version 3?

Currently I am using the following to get the address on the message. 

```
anonymous.Connect("inproc://example");
anonymous.Send("ROUTER uses a generated UUID", Encoding.Unicode);
var messsage = sink.ReceiveMessage();
Console.WriteLine("ZMQ set: {0}", Encoding.Unicode.GetString(messsage[0].Buffer));
```

Can I assume that the address created by ZMQ in this case is Unicode encoded?

**Comment by jgoz** [comment]
@staticcat 

> ```
> ZHelpers.Dump(sink, Encoding.Unicode);
> ```
> 
> What would be the replacement for this in version 3?

There is no replacement for this in version 3. It didn't really make sense to have as part of the core clrzmq API, so it was removed. You'll have to re-implement an equivalent in your code based on [the original source](https://github.com/zeromq/clrzmq/blob/2.2/src/clrzmq/Util.cs).

> Can I assume that the address created by ZMQ in this case is Unicode encoded?

I'm not 100% sure how routers generate IDs, but If it is generating a UUID it will be encodable as ASCII or UTF-8.

**Comment by tjrobinson** [comment]
If you re-implement it please let me know as it will be useful for re-writing the current samples (still in progress, just delayed by unexpected events).

**Comment by staticcat** [comment]
OK here's another one I have come across. 

```
ZHelpers.SetID(worker, Encoding.Unicode);
```

Currently I am using the following. 

```
worker.Identity = Encoding.Unicode.GetBytes(Guid.NewGuid().ToString());
```

Seems a little overkill though. Any other suggestions on what to use?

**Comment by staticcat** [comment]
@tjrobinson added a gist of the [dump method](https://gist.github.com/4138978)

**Comment by tjrobinson** [comment]
I've updated the samples (they don't build yet):
https://github.com/tjrobinson/zguide/tree/clrzmqv3/examples/C%23

Can anyone help with the various remaining issues? I'm confused by the IOMultiPlex/Poller/PollItem changes.

**Comment by staticcat** [comment]
Sure drop me a line with the code that is causing confusion. Might have already fixed it in the examples I have updated (sadly not as complete as yours).

**Comment by tjrobinson** [comment]
@staticcat I think I've resolved the issues now. Everything now compiles so the final step is to check the samples still work as expected.

**Comment by tjrobinson** [comment]
The samples I've updated have been pulled into the main zguide repo now. There are probably still some problems though, as I didn't have a chance to test them all.

I think this particular issue can probably be closed? At least from a clrzmq point of view?

**Comment by staticcat** [comment]
Sounds good to me. I will get around to reviewing them and if I see any issues I will simply update.
