### ISSUE TITLE
Poll() no longer returns readycount.

### ISSUE THREAD

**Issue by staticcat** [zeromq/clrzmq#86]
I am trying to use an example from the ZGuide and also reading through the source of the main branch. 

I am trying to implement a lazy pirate client and server. 

http://zguide.zeromq.org/cs:lpserver
http://zguide.zeromq.org/cs:lpclient

In the client the following code is required to test if the connection has been dropped. 

``` C#
                    while (expectReply)
                    {
                        int count = Context.Poller(requestTimeout * 1000, client);

                        if (count == 0)
                        {
                            retriesLeft--;
```

The poller has changed to be its own object, and the Poll call off it no longer returns a count. This count seems to be the ready count of sockets that were polled. 

How is this meant to be called in the new API?

**Comment by jgoz** [comment]
This has been omitted from the new API, though not on purpose. I will add a return value to `Poller.Poll` methods. Thanks for the good catch.
