### ISSUE TITLE
Behaviour of timeout on Context.Poll doesn't match the documentation

### ISSUE THREAD

**Issue by johnsietsma** [zeromq/clrzmq#9]
The comment above Context.Poll(PollItem[] items) claims it will to poll with an immediate timeout. In fact, it passes -1 to zmq_poll which waits indefinitely. It should pass a 0 instead.

**Comment by Guthur** [comment]
Thanks for catching that.

It should have read infinite timeout.

Please comment if you think it should be implemented the other way. I had intended it to be infinite though.

**Comment by johnsietsma** [comment]
Infinite is fine. It just tripped me up when I took the comment at face value.
