### ISSUE TITLE
clrzmq allocates each time a message is received or sent.

### ISSUE THREAD

**Issue by rverdier** [zeromq/clrzmq#90]
Hello,

First of all, clrzmq works great ; thanks to everyone involved in the project.

Now, I'm well aware that the issue I'm talking about here is something that many people won't really care about: avoiding allocations in a managed library can seem a bit meaningless at first sight.

However, 0mq is by design a transport layer meant to be used in high-performance and low-latency applications. Even in .NET and Java world, we are starting to see such "pseudo real-time" applications with very strong latency constraints. These applications try to minimize (or even prevent completely) garbage collection during the program lifetime by managing (or avoiding) allocations very carefully: object pooling, use of value types, avoiding boxing, custom serialization, etc.

For instance, 29west (now Informatica) managed messaging solution provides a "Zero Object Delivery" API for both Java and .NET, wich allows... 

> "...Java/.NET messaging receivers to deliver messages to an application without creating  per-message objects. This allows you to write Java/.NET receiving applications that require little to no garbage collection at runtime, producing lower and more consistent message latencies for your Java/.NET applications."

In its current state, clrzmq is very close to be allocation free. I just wanted to discuss about that. I actually spotted two main remaining sources of allocations, that could easily be eliminated:
- All lambdas passed as arguments during calls to the static method `SocketProxy.RetryIfInterrupted` close over local variables and fields. The compiler generates an inner class for the closure needs and allocates each time the method is called.
- Still in `SocketProxy` class, `Send`, `Receive` and `Forward` methods instanciates `ZmqMsgT`reference type.

It's quite easy to fix, even if that implies writing slightly less intuitive code (see details below). Basic tests would not really show any significant performance gain in pure 0mq sample apps, but we need to take into consideration that GC pauses impact the whole process. That means that in the context of a real world, latency sensitive application, the GC can have a more visible effect.
### Avoiding closures

First, we can bypass allocations by avoiding closures. One way to do so is to create some overloads to the method `RetryIfInterrupted`, that also takes as arguments everything that is needed in the func scope. That's not very fancy but works pretty well and allows the client code to remain readable. 

For example, if we define the following method:

``` C#
private static int RetryIfInterrupted<T1, T2, T3, T4>(T1 t1, T2 t2, T3 t3, T4 t4, Func<T1, T2, T3, T4, int> func)
{
    int rc;
    do
    {
        rc = func(t1, t2, t3, t4);
    }
    while (rc == -1 && LibZmq.zmq_errno() == ErrorCode.EINTR);
    return rc;
}
```

We can replace such a call:

``` C#
RetryIfInterrupted(() => LibZmq.zmq_buffer_send(SocketHandle, _sendIntPtrBuffer, sizeToSend, flags));
```

By something like that:

``` C#
RetryIfInterrupted(SocketHandle, _sendIntPtrBuffer, sizeToSend, flags, (sh, sb, s, f) => LibZmq.zmq_buffer_send(sh, sb, s, f));
```

That's not ideal for sure, but it limits the code redundancies we would have by inlining every `RetryIfInterrupted` calls.
### Merging `ZmqMsgT`and `DisposableIntPtr`

If we don't want to allocate on the heap a `ZmqMsgT` instance each time we receive or send a message, we can reuse instances (easy since `ZmqSocket` doesn't have to be thread safe) or make `ZmqMsgT` a value type. I did a quick spike where I merged `ZmqMsgT` functionality into `DisposableIntPtr`. Even if the struct `DisposableIntPtr` implements `IDisposable`, it won't be boxed on disposing because of the constrained virtual call emmited by the compiler in this case.

Of course this is only a basic attempt/suggestion, I barely scratched the surface of the code base so it may well exist a better way to achieve the same goal.

I can totally submit a pull request with the changes discussed before, but I wanted to discuss it with you upfront. Let me know what you think.

Again, thanks for your work.

**Comment by jgoz** [comment]
Hi @rverdier, thank you very much for the review! I agree that performance trumps readability in this kind of library, so any marginal performance improvements would be most welcome.

`ZmqMsgT` allocation is something I keep changing my mind about. Like you say, `ZmqSocket` is not thread-safe, so we could just allocate message pointers when a socket is constructed and re-use them throughout, cleaning them up when the socket is disposed. On the other hand, I am curious about your "`ZmqMsgT` as a value type" approach.

Can you please submit two pull requests? One that handles `RetryIfInterrupted` and one that handles `ZmqMsgT`? This will help me test/tweak them independently.

Once again, thank you for the review!
