### ISSUE TITLE
Clrzmq2.2 platform version 64   Need to MonoPosixHelper. DLL 64 position, but I can't find，Please emergency help

### ISSUE THREAD

**Issue by zlj1817** [zeromq/clrzmq#91]
Clrzmq2.2 platform version 64   Need to MonoPosixHelper. DLL 64 position, but I can't find，Please emergency help。
Error information below：

Server Error in '/' Application.

Unable to load DLL 'MonoPosixHelper': Can't find the specified module。 (Exception from HRESULT: 0x8007007E)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.DllNotFoundException: Unable to load DLL 'MonoPosixHelper':Can't find the specified module。 (Exception from HRESULT: 0x8007007E)

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[DllNotFoundException: Unable to load DLL 'MonoPosixHelper': Can't find the specified module。 (Exception from HRESULT: 0x8007007E)]
   Mono.Unix.Native.NativeConvert.FromSignum(Signum value, Int32& rval) +0
   Mono.Unix.UnixSignal..ctor(Signum signum) +49
   ZMQ.SignalHandler.Initialize() +114
   ZMQ.SignalHandler.StartHandler() +130
   ZMQ.Context..ctor() +52
   SearchProxy.SendQuery(String EndPoint, String Type, String QueryString) +92
   SearchProxy.Query(String Type, String QueryString) +59
   _Default.Page_Load(Object sender, EventArgs e) +48
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +25
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3064

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.272

**Comment by jgoz** [comment]
Hi,

Are you running this on Windows with the .NET Framework, or are you using Mono on Linux?

If on Windows, make sure you are using a clrzmq build that was created for Windows. If you compiled it yourself, make sure the `POSIX` compiler flag was _not_ specified.

If on Linux, you will need to have Mono 2.6+ installed. Any version less than that may not work correctly with clrzmq.

**Comment by zlj1817** [comment]
created for Windows，but select  “win_release”， Cannot normal formation。
Once again open project attributes, and choose the POSIX options，Don't know what reason be。

**Comment by jgoz** [comment]
In the clrzmq project, can you delete `Mono.Posix` from the References and recompile it with the WIN_RELEASE configuration?

**Comment by zlj1817** [comment]
I according to your method operation, can the normal generation x64 library, but in iis can not run inside.

Error information below：

[BadImageFormatException: Trying to load format is not correct procedure. (Anomaly from HRESULT:0x8007000B)]
   ZMQ.C.zmq_init(Int32 io_threads) +0
   ZMQ.Context..ctor() in C:\Users\Administrator\Desktop\WebSite1\src\clrzmq\Context.cs:87
   website.SearchProxy.SendQuery(String EndPoint, String Type, String QueryString) in C:\Users\Administrator\Desktop\WebSite1\website\website\Default.aspx.cs:47
   website.SearchProxy.Query(String Type, String QueryString) in C:\Users\Administrator\Desktop\WebSite1\website\website\Default.aspx.cs:30
   website._Default.Page_Load(Object sender, EventArgs e) in C:\Users\Administrator\Desktop\WebSite1\website\website\Default.aspx.cs:20
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +25
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3064

**Comment by zlj1817** [comment]
Clrzmq2.2 corresponding x64 libzmq. DLL, where can I get it?
Recent tests found that Clrzmq2.2 x64 in call x86 libzmq. DLL lead to mistakes!

**Comment by jgoz** [comment]
You can download clrzmq2.2 releases from here: https://github.com/zeromq/clrzmq/downloads

`clrzmq-x64.2.2.5.zip` is for x64 and includes 64-bit libzmq.dll

`clrzmq.2.2.5.zip` is for x86 and includes 32-bit libzmq.dll

**Comment by zlj1817** [comment]
I downloaded, and tested and normal operation, thank you very much
