### ISSUE TITLE
libzmq 3.2.1 api change

### ISSUE THREAD

**Issue by hyh** [zeromq/clrzmq#94]
per https://raw.github.com/zeromq/zeromq3-x/master/NEWS
- zmq_ctx_set_monitor () replaced by zmq_socket_monitor ().

This is a breaking change in libzmq 3.2.1 and causing clrzmq failed to load.
Following is the exception I got:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'ZeroMQ.Interop.LibZmq' threw an exception. ---> System.MissingMethodException: Unable to find function 'zmq_ctx_set_monitor' in dynamically loaded library.
   at ZeroMQ.Interop.UnmanagedLibrary.GetUnmanagedFunction[TDelegate](String functionName)
   at ZeroMQ.Interop.LibZmq..cctor()
   --- End of inner exception stack trace ---
   at ZeroMQ.Interop.ContextProxy.Initialize()
   at ZeroMQ.ZmqContext.Create()

**Comment by jgoz** [comment]
Thanks for catching that - I was ahead of the 3.2.1-rc2 release by about 6 hours :)
