### ISSUE TITLE
3.2.1-beta3 NuGet installation requires MSVCP110.dll 

### ISSUE THREAD

**Issue by staticcat** [zeromq/clrzmq#99]
Seems that the dll built and released as part of the Net40 lib requires MSVCP110.dll. Seems to be related to visual studio 11 beta. I just am working with Visual Studio 10, however I didn't think this would matter.

**Comment by staticcat** [comment]
Building the libzmq myself on Visual Studio 10 and using that dll removes this issue. What does this mean for development on older (now that VS 11 has been released) IDE's?

**Comment by tjrobinson** [comment]
@jgoz has said in this comment (https://github.com/zeromq/clrzmq/issues/81#issuecomment-9671639) that libzmq.dll will be built using VS2010 instead ov VS2011 for the next release. So this problem should go away.

**Comment by staticcat** [comment]
Awesome. Building it myself works for the time being so no rush from me.

**Comment by staticcat** [comment]
Great too hear, will test it ASAP.

**Comment by staticcat** [comment]
I have updated and works. Thanks for the release and patch.
